In [177]:
"""
📊 Practice Problem: Incomplete Survey Cleanup

🎯 Tasks:
	1.	Drop rows where all values except 'respondent' are missing.
	2.	Fill missing age values with the mean age.
	3.	Fill missing income with the median income.
	4.	Fill missing country with the string "Unknown"
"""
import pandas as pd 

df = pd.DataFrame({
    'respondent': [1, 2, 3, 4, 5],
    'age': [25, None, 30, None, 22],
    'income': [50000, 60000, None, None, 45000],
    'country': ['US', 'Canada', 'US', None, 'Canada']
})

new_df = df[((df['age'].notna()) | (df['income'].notna()) | (df['country'].notna())) 
            & (df['respondent'].notna())]

new_df = new_df.copy()

new_df['age'] = new_df['age'].fillna(new_df['age'].mean())
new_df['income'] = new_df['income'].fillna(new_df['income'].median())
new_df['country'] = new_df['country'].fillna('Unknown')

new_df

   respondent        age   income country
0           1  25.000000  50000.0      US
1           2  25.666667  60000.0  Canada
2           3  30.000000  50000.0      US
4           5  22.000000  45000.0  Canada

In [163]:
import pandas as pd

df = pd.DataFrame({
    'employee': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'department': ['HR', 'HR', 'Finance', 'HR', 'HR', 'Finance'],
    'year': [2022, 2022, 2022, 2023, 2023, 2023],
    'score': [85, 88, 90, 87, 84, 91]
})

# new_df = df.groupby(['department', 'year'])['score'].mean().reset_index()

pd.pivot_table(df, index=['department'], columns='year', values='score', aggfunc='mean').reset_index()

year department  2022  2023
0       Finance  90.0  91.0
1            HR  86.5  85.5

In [145]:
"""
📊 Practice Problem: Course Completion Tracker

🎯 Tasks:
	1.	Filter to only rows where "completed" == True
	2.	For each student, calculate:
	•	The number of completed courses
	•	Their average score across completed courses
	3.	Return a DataFrame with:

student | courses_completed | avg_score
"""

import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie', 'Alice'],
    'course': ['Math', 'Math', 'Math', 'English', 'English', 'English', 'History'],
    'completed': [True, True, False, True, False, True, False],
    'score': [88, 76, None, 92, None, 85, None]
})

(
    df[df['completed']]
    .groupby('student')
    .agg({'course': 'count', 'score': 'mean'})
    .reset_index()
    .rename(columns={'course': 'course_count', 'score': 'avg_score'}))

   student  course_count  avg_score
0    Alice             2       90.0
1      Bob             1       76.0
2  Charlie             1       85.0

In [139]:
"""
🎯 Tasks:
	1.	Merge the two DataFrames to include employee name, department, year, and score.
	2.	Compute the average review score per department.
	3.	Output a DataFrame:

department | avg_score

"""
import pandas as pd

employees = pd.DataFrame({
    'emp_id': [101, 102, 103, 104, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eli'],
    'department': ['HR', 'IT', 'IT', 'Finance', 'HR']
})

reviews = pd.DataFrame({
    'emp_id': [101, 102, 102, 104, 105, 105],
    'year': [2022, 2022, 2023, 2022, 2022, 2023],
    'score': [3.9, 4.2, 4.5, 3.5, 4.0, 4.1]
})


df = pd.merge(employees, reviews, how="inner", on='emp_id', suffixes=('_x','_y'))
df.groupby('department')['score'].mean().reset_index().rename(columns={'score': 'avg_score'})

  department  avg_score
0    Finance       3.50
1         HR       4.00
2         IT       4.35

In [ ]:
"""
📊 Practice Problem: Review Scores Summary

🎯 Tasks:
	1.	Filter the DataFrame to include only verified reviews.
	2.	Group by "product" and calculate the average review score.
	3.	Return a DataFrame sorted by average score descending, with columns:

product | avg_score
"""

import pandas as pd

df = pd.DataFrame({
    'product': ['A', 'A', 'A', 'B', 'B', 'C', 'C', 'C', 'C'],
    'review_score': [5, 4, 5, 3, 2, 4, 4, 5, 3],
    'verified': [True, False, True, True, False, True, False, True, True]
})

new_df = df[df['verified'] == True].groupby('product')['review_score'].mean().rename(columns={'review_score': 'avg_score'}).sort_values(by='avg_score', ascending=False).reset_index()
new_df[['product', 'avg_score']]

  product  avg_score
0       A        5.0
1       C        4.0
2       B        3.0

In [124]:
"""
🧠 Practice: Normalize and Filter Words

🎯 Task:
	1.	Normalize each sentence:
	•	Remove extra spaces
	•	Convert all words to lowercase
	2.	Flatten all the words into one list
	3.	Keep only words longer than 3 characters

⸻

Expected output (approx):

['data', 'powerful', 'python', 'great', 'data', 'analysis', 'data', 'analysis']

"""

sentences = [
    "  Data is powerful ",
    "Python is GREAT for data analysis ",
    "DATA   analysis is fun"
]

output = [w for s in sentences for w in s.strip().lower().split() if len(w) > 3]
output

['data', 'powerful', 'python', 'great', 'data', 'analysis', 'data', 'analysis']

In [76]:
"""
📊 Practice Problem: Flag Students at Risk
⸻

🎯 Tasks:
	1.	For each student, compute their average score across all subjects.
	2.	Add a new column: "at_risk" — set to True if their average is below 70, else False.
	3.	Return a DataFrame like:

student   avg_score   at_risk
Alice     65.0        True
Bob       71.0        False
Charlie   82.5        False
"""

import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie', 'Alice'],
    'subject': ['Math', 'Math', 'Math', 'English', 'English', 'English', 'History'],
    'score': [85, 72, 90, 60, 70, 75, 50]
})

new_df = df.groupby('student')['score'].mean().reset_index().rename(columns={'score': 'avg_score'})

new_df['at_risk'] = new_df['avg_score'].apply(lambda x: x < 70)
new_df

   student  avg_score  at_risk
0    Alice       65.0     True
1      Bob       71.0    False
2  Charlie       82.5    False

In [ ]:
"""

📊 Practice Problem: Top Scorer per Subject

⸻

🧠 Tasks:
	1.	For each subject, find the student(s) with the highest score.
	2.	Output a DataFrame with columns:

subject | student | score

	3.	Bonus: Sort the result by subject alphabetically.

"""
import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'subject': ['Math', 'Math', 'Math', 'English', 'English', 'English'],
    'score': [88, 79, 93, 85, 90, 87]
})
idx = df.groupby('subject')['score'].idxmax()

output = df.loc[idx]
output

   student  subject  score
4      Bob  English     90
2  Charlie     Math     93

In [55]:
"""
🧠 Practice Problem: Match Students with Their Grades

Tasks:
	1.	Merge the two DataFrames so each student is matched with their subjects and scores.
	2.	Filter the result to only include scores ≥ 90.
	3.	Sort the result by score in descending order.

Expected columns:

student_id | name | subject | score
"""
import pandas as pd

students = pd.DataFrame({
    'student_id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie']
})

grades = pd.DataFrame({
    'student_id': [1, 1, 2, 3, 3],
    'subject': ['Math', 'English', 'Math', 'English', 'Science'],
    'score': [85, 88, 79, 92, 95]
})

df = pd.merge(students, grades, how='inner', on='student_id')
df[df['score']>=90]

   student_id     name  subject  score
3           3  Charlie  English     92
4           3  Charlie  Science     95

In [52]:
"""
Great — here’s a focused pandas practice that uses filtering, grouping, and basic aggregation.

⸻

📊 Practice Problem: Average Scores by Subject

	1.	Filter the DataFrame to only include scores above 80.
	2.	Group by subject and compute the average score.
	3.	Reset the index of the result so it’s a flat DataFrame.

Expected output structure:

   subject  avg_score
0  English       86.0
1     Math       85.0
2  Science       89.0

"""
import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob'],
    'subject': ['Math', 'Math', 'Science', 'Science', 'English', 'English'],
    'score': [85, 78, 90, 88, 92, 80]
})

df[df['score'] > 80].groupby('subject', as_index=False)['score'].mean().rename(columns={'score': 'avg_score'})

   subject  avg_score
0  English       92.0
1     Math       85.0
2  Science       89.0

In [42]:
"""
🧠 Practice Problem: Extract Words with More Than 3 Letters

Task:
	1.	Use a list comprehension to extract all words longer than 3 characters.
	2.	Flatten all the words from all sentences into one list.
	3.	Your result should look something like:

['data', 'powerful', 'python', 'great', 'data', 'analysis', 'data', 'analysis']

"""

sentences = [
    "data is powerful",
    "python is great for data analysis",
    "data analysis is fun"
]


output = [x for s in sentences for x in s.split() if len(x)>3]
output

['data', 'powerful', 'python', 'great', 'data', 'analysis', 'data', 'analysis']

In [37]:
"""
	1.	Use a list comprehension to:
	•	Split each sentence into words.
	•	Flatten all the words into a single list.

output
['data', 'is', 'powerful', 'python', 'is', 'great', 'for', 'data', 'analysis', 'data', 'analysis', 'is', 'fun']    
"""

sentences = [
    "data is powerful",
    "python is great for data analysis",
    "data analysis is fun"
]

output = []

# for s in sentences:
#     spl = s.split()
#     for w in spl:
#         output.append(w)

l = [w for s in sentences for w in s.split()]
# l = {w for s in sentences for w in s.split()}

l 

# output

['data',
 'is',
 'powerful',
 'python',
 'is',
 'great',
 'for',
 'data',
 'analysis',
 'data',
 'analysis',
 'is',
 'fun']

In [ ]:
"""
Objective: Write a Python script that counts how many times each word appears in a list of sentences.

output:
{'data': 3, 'is': 3, 'powerful': 1, 'python': 1, 'great': 1, 'for': 1, 'analysis': 2, 'fun': 1}
"""
sentences = [
    "data is powerful",
    "python is great for data analysis",
    "data analysis is fun"
]

output = {}
for s in sentences:
    spl = s.split()
    for w in spl:
        output[w] = output.get(w, 0) + 1
        
# output


"""
Follow up Task:
Using your previous word count output dictionary, do the following with pandas:
	1.	Convert the dictionary into a DataFrame with columns:
	•	"word" (the word)
	•	"count" (how many times it appeared)
	2.	Sort the DataFrame by "count" in descending order.
	3.	Bonus: Filter to show only words that appear more than once.

output:
      word  count
0     data      3
1       is      3
2  analysis      2
...
"""
import pandas as pd

as_df = pd.DataFrame(list(output.items()), columns=['word', 'count']).sort_values(by='count', ascending=False).reset_index(drop=True)
df = as_df[as_df['count'] > 1]
df

       word  count
0      data      3
1        is      3
2  analysis      2

In [10]:
""" 
💻 Problem: Tuple squares

Write a list comprehension that creates a list of 
tuples in the form (n, n²) for numbers from 1 to 10.
...this problem is a variation of the one below

[(1, 1), (2, 4), (3, 9), ..., (10, 100)]
"""
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# result = [(n, n**2) for n in nums]
# result

"""
dictionary version
"""
result = {n:n**2 for n in nums}
result

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [17]:
"""
Write a list comprehension that takes a list of integers 
and returns a new list with the squares of the odd numbers only.

nums = [1, 2, 3, 4, 5, 6, 7]
# result: [1, 9, 25, 49]

"""

nums = [1, 2, 3, 4, 5, 6, 7]

result = [n**2 for n in nums if n % 2 != 0]
result

[1, 9, 25, 49]

In [ ]:
"""
Write a function that takes a sentence and returns a list of all words that:
	1.	Are longer than 3 characters
	2.	Start with a vowel (a, e, i, o, u)
	3.	Are converted to lowercase

sentence = "Apples are excellent, but Oranges often outshine"
result = vowel_words(sentence)
print(result)  # ['apples', 'excellent', 'oranges', 'often', 'outshine']
"""

sentence = "Apples are excellent, but Oranges often outshine Excellent!"

def vowel_words(sentence):
    vowels = ['a','e','i','o','u']
    result = []
    for s in sentence.split():     # i think this should fix it...
        s = s.lower().strip(',.!')
        if (len(s) > 3) and (s[0] in vowels):
            result.append(s)
    return result

vowel_words(sentence)

# Great! Here’s a cleaner version that also:

# ✅ Removes punctuation
# ✅ Handles capitalization
# ✅ Handles edge cases like "Excellent!" or "apples."

['apples', 'excellent', 'oranges', 'often', 'outshine', 'excellent']

In [ ]:
"""
Write a for loop that:
	1.	Converts each temperature to Fahrenheit (F = C * 9/5 + 32)
	2.	Appends only the Fahrenheit values that are above 75°F to a new list called hot_days_f.
"""
# temps = [22, 25, 19, 24, 28, 21, 23]
# hot_days_f = []

# for t in temps:
#     f = (t*(9/5) + 32)
#     if f > 75:
#         hot_days_f.append(f)

# hot_days_f

"""
bonus - append both F and C in a dictionary {C:F}
"""
temps = [22, 25, 19, 24, 28, 21, 23]

hot_days = {}

for t in temps:
    f = (t*(9/5) + 32)
    if f > 75:
        hot_days[t] = f 

hot_days

{25: 77.0, 24: 75.2, 28: 82.4}

In [ ]:
# You’re given a list of filenames. Write a loop that builds a dictionary where:
# 	•	Each key is a file extension (like 'txt', 'csv', 'jpg')
# 	•	Each value is the number of times that extension appears

files = [
    "report.csv", "data.csv", "image.jpg", "notes.txt",
    "summary.txt", "presentation.ppt", "photo.jpg"
]

solution = {}


for f in files:
    extensions = f[-3:]
    solution[extensions] = solution.get(extensions,0) + 1

solution

{'csv': 2, 'jpg': 2, 'txt': 2, 'ppt': 1}

In [ ]:
# Write a loop that:
# 	•	Tallies how many names start with each letter
# 	•	Uses .get() to safely update counts in a dictionary

names = [
    "Alice", "Aaron", "Bob", "Brenda", "Charlie", "Catherine", "David", "Diana"
]

first_letter = []
solution = {}

for n in names:
    k = n[0]
    solution[k] = solution.get(k,0) + 1

solution

{'A': 2, 'B': 2, 'C': 2, 'D': 2}

In [2]:
# Use a for loop to tally how many votes each candidate received

votes = [
    'Alice', 'Bob', 'Alice', 'Eve', 'Bob', 'Alice', 'Eve', 'Eve', 'Bob', 'Alice'
]

votes_dict = {}

for v in votes:
    votes_dict[v] = votes_dict.get(v, 0) + 1

votes_dict

{'Alice': 4, 'Bob': 3, 'Eve': 3}

In [ ]:
# Task:
# Write a Python function that takes a list of strings (sentences) and returns a dictionary 
# with the frequency of each word (case-insensitive).


sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "The dog barked, and the fox ran away!"
]
s_list = []

for s in sentences:
    s_split = s.split()
    for w in s_split:
        s_list.append(w.lower().strip(',.!'))

s_unique = []
for word in s_list:
    if word not in s_unique:
        s_unique.append(word)

a_dict = {}
for j in s_unique:
    a_dict[j] = s_list.count(j)

a_dict

{'the': 4,
 'quick': 1,
 'brown': 1,
 'fox': 2,
 'jumps': 1,
 'over': 1,
 'lazy': 1,
 'dog': 2,
 'barked': 1,
 'and': 1,
 'ran': 1,
 'away': 1}

In [33]:

vowels = ['a','e','i','o','u']
words = ['apple', 'sky', 'education', 'loop']
solution = []
for w in words:
    counter = 0
    for l in w:
        if l in vowels:
            counter += 1
    solution.append(counter)

solution

[2, 0, 5, 2]

In [39]:
# get longest word in a text
text = "Learning Python with practicing builds strong coding muscle memory"
words = text.split()
lengths = []
for w in words:
    lengths.append(len(w))

biggest = max(lengths)
lengths.index(biggest)

3

In [ ]:
"""
Find the distance between the two furthest apart values in a list.
Create a dist function, receiving a list of numbers (integers or floating points), 
and returning the bigger distance between any two given values, 
so typically the distance between the biggest and the smallest, like:
>>> dist([1, 2, 3])
2
"""

In [ ]:
"""
Write a function named from_roman_numeral that return the value of a given roman numeral.

if next > curr, then -=curr
else +=curr
upper...

"""

roman_str = 'XLIX'

def from_roman_numeral(roman_str):
    conversion = {'I':1, 'V':5, 'X':10, 'L':50 ,'C':100,'M':1000}
    value = 0
    for n in range(len(roman_str)): # determine value, and add to total
        val = conversion[roman_str[n]]
        if n+1 < len(roman_str): 
            next_val = conversion[roman_str[n+1]]
            if val < next_val:
                value -= val
                continue
        value += val

    return(value)

from_roman_numeral(roman_str)
# can this be shortened using tech support?

49

In [ ]:
"""
Write a function named to_roman_numeral that converts integers to roman numerals.

"""

to_numeral = 24

conversion = {1000:'M', 100:'C', 50:'L', 10:'X', 5:'V', 1:'I' }
num_list = list(conversion.keys())
output = ''

while to_numeral > 0:

    max_key = max([x for x in num_list if x <= to_numeral], default=1)
    max_val = conversion[max_key]
    max_key_prior = num_list.index(max_key) - 1      # account for errors when this doesnt exist
    max_val_prior = conversion[num_list[max_key_prior]]

    output += max_val
    if 4 * max_key <= to_numeral:
        output += max_val_prior
        to_numeral -= 4 * max_key
    else:
        to_numeral -= max_key
        
    

output

'XXIV'

In [109]:
"""
You found a safe. There's a numeric keypad on it...
The keypad is dirty, thanks to this you can easily spot that numbers 1, 5, and 8 are frequently used. 
It's so clear that you guess no other digit is in use in this code.
Write a script printing all combinations of 4 digits that use all of those used digits.
Output one combination per line, separate digits using spaces, so your output should look like:
1 1 5 8
1 5 5 8
1 5 8 8
"""

"\nYou found a safe. There's a numeric keypad on it...\nThe keypad is dirty, thanks to this you can easily spot that numbers 1, 5, and 8 are frequently used. \nIt's so clear that you guess no other digit is in use in this code.\nWrite a script printing all combinations of 4 digits that use all of those used digits.\nOutput one combination per line, separate digits using spaces, so your output should look like:\n1 1 5 8\n1 5 5 8\n1 5 8 8\n"

In [ ]:
"""
Write a function combining two strings so they are displayed side by side, separated by a column of pipe (|) symbols, like this:
Lorem ipsum dolor sit amet, consectetur|Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Sed non risus.        |adipiscing elit. Sed non risus.        
Suspendisse lectus tortor, dignissim   |Suspendisse lectus tortor, dignissim   
sit amet, adipiscing nec, utilisez sed |sit amet, adipiscing nec, utilisez sed 
sin dolor.                             |sin dolor. 

This function will also take a 3rd, optional, parameter named width representing the maximum width allowed, defaulting to 79, so the function prototype is:
"""

In [ ]:
"""
Implement the fill_magic_square function.
It takes a single argument: a numpy.array of integers representing a partially filled magic square. Holes are represented using zeros.
Your fill_magic_square function will have to find and fill the gaps in the square.
Do not return a value, just modify the square in-place.
Beware, my magic squares may contain any natural number (> 0), I do not restrict myself to magic squares with numbers from 1 to square_size ** 2.

easy_square = np.array([
    [2, 7, 6],
    [9, 0, 1],
    [4, 3, 8],
])
fill_magic_square(easy_square)
print(easy_square)

Should give:
array([[ 2, 7, 6 ],
       [ 9, 5, 1 ],
       [ 4, 3, 8 ]]])

"""

##### **Hangman ---> Python game by E**

In [ ]:
# num_letters = int(input("welcome to hell...I mean, hangman. Six wrong guesses and I win. hahaha...how many letters do you want the answer to have? "))

# # generate a word with num_letters letters
# answer_string = "doggy"
# answer_list = []
# starting_list = []

# for a in answer_string:
#     answer_list.append(a)

# for s in range(num_letters):
#     starting_list.append("-")

#     # change the above to a string? "-"

# # other variables
# guess_list = []
# chances = 6
# chance_counter = 0

In [ ]:
# guess = input(f"the word is {starting_list}. You get {chances} chances - guess a letter, or guess the word: ")
# if guess == answer_string:
#     print("damn, you're good. I quit!")

# while (guess != answer_string) & (chance_counter < 6) & (starting_list != answer_list):
#     # word is selected
#     if len(guess) > 1:

#     # word is correct
#         if guess == answer_string:
#             print("you WIN!")

#     # word is incorrect
#         else:
#             chance_counter += 1
#             guess = input(f"nope! that's {chance_counter} out of 6 guesses. guess a letter, or the word: {starting_list}")


#     # letter is selected
#     else:
#         if guess in guess_list:
#             guess = input(f"you guessed that letter already - try a different one {starting_list}: ")
#     # letter is correct
#         elif guess in answer_string:
#             yes_list = []
#             guess_list.append(guess)
#             for letter_ind in range(len(answer_list)):
#                 if answer_list[letter_ind] == guess:
#                     yes_list.append(letter_ind)
            
#             for m in yes_list:
#                 starting_list[m] = guess
#             if starting_list == answer_list:
#                 print("well played. I concede - you win.")        
#                 break  
#             else:
#                 guess = input(f"Sure, that letter's in there: {starting_list}. guess a letter, or the word: ")

    
#     # letter is incorrect
#         else:
#             guess_list.append(guess)
            
#             if chance_counter == 6:
#                 print("Got 'eeeeem! I win")
#                 break
#             else:
#                 guess = input(f"nope! that's {chance_counter} out of 6 guesses. guess a letter, or the word: {starting_list}")
#                 chance_counter += 1

well played. I concede - you win.

In [ ]:
# # Provide a script that prints the number of words in the given paragraph.
# # I prefilled the answer box with the paragraph, in a variable, but in case you lose it, here it is:

# #   - remove punctuation
# #   - all lowercase

# # whetting_your_appetite = "Python is an easy to learn, powerful programming language. It has efficient high level data structures and a simple but effective approach to object oriented programming. This tutorial introduces the reader informally to the basic concepts and features of the Python language and system. For a description of standard objects and modules..."
# word_count = "I am using Python. This is a string with has words. I am counting the words, words, words, using python python python python python"

# word_split = word_count.split()
# counter = 0

# # count total words
# word_list = []
# for word in word_split:
#     word_list.append(word.lower().strip(".,"))
#     counter += 1

# counter
# # word_list

# # can you also count the number of each word - output as a list

# deduped = []
# for i in word_list:
#     if i not in deduped:
#         deduped.append(i)
#     else:
#         deduped = deduped

# # deduped

# word_dict = {}

# for k in deduped:
#     val = 0
#     for v in word_list:
#         if k == v:
#             val += 1
#         word_dict[k] = val

# word_dict

24

In [ ]:
# # Ask the user for a number and determine whether the number is prime or not. 

# num = int(input("let's check a numbers prime-ability. enter one: "))
# counter = 0
# factors = []
# for i in range(1, num + 1):
#     if num % i == 0:
#         counter += 1
#         factors.append(i)
#     else:
#         counter = counter

# print(counter)
# print(factors)
# if counter <= 2:
#     print("PRIME")
# else:
#     print("unprime")

4
[1, 3, 127, 381]
unprime