In [174]:
# import pandas as pd

# filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"
# df = pd.read_csv(filename)
# df.head()
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

np.dot(arr1, arr2)
# arr1.shape

np.int64(4900)

In [161]:
class Graph():
    def __init__(self, id):
        self.id = id
        # self.id = 80


val = Graph(200)
print(val.id)

200

In [ ]:
import pandas as pd
from datetime import datetime

def generate_date_dim(start_date='2000-01-01', end_date='2050-12-31', holidays=None):
    dates = pd.date_range(start=start_date, end=end_date, freq='D')
    df = pd.DataFrame({'date': dates})
    
    df['id'] = df['date'].dt.strftime('%Y%m%d').astype(int)
    df['date'] = df['date'].dt.date
    df['Full date'] = df['date'].apply(lambda x: x.strftime('%B %-d, %Y'))  # e.g., April 5, 2025
    df['year'] = pd.DatetimeIndex(df['date']).year
    df['Week ending date'] = df['date'] + pd.to_timedelta((5 - df['date'].apply(lambda x: x.weekday())) % 7, unit='D')  # Saturday as week end
    df['Day of week'] = df['date'].apply(lambda x: x.strftime('%A'))
    df['Week of year'] = pd.DatetimeIndex(df['date']).isocalendar().week
    df['month number'] = pd.DatetimeIndex(df['date']).month
    df['Month name'] = df['date'].apply(lambda x: x.strftime('%B'))
    df['Day of month'] = pd.DatetimeIndex(df['date']).day
    df['Month ending date'] = pd.to_datetime(df['date']).apply(lambda x: x.replace(day=1) + pd.offsets.MonthEnd(0)).dt.date
    df['Day of year'] = pd.DatetimeIndex(df['date']).dayofyear
    df['Quarter'] = pd.DatetimeIndex(df['date']).quarter
    df['Is_weekend flag'] = df['Day of week'].isin(['Saturday', 'Sunday'])
    
    # Holiday logic (add your list of holidays as 'YYYY-MM-DD')
    holidays = holidays or []
    holiday_dates = pd.to_datetime(holidays).date
    df['Is_holiday flag'] = df['date'].isin(holiday_dates)
    
    return df

1

In [146]:

cart = [
    {"item": "Laptop", "price": 1200, "quantity": 1, "category": "Electronics"},
    {"item": "Book", "price": 25, "quantity": 3, "category": "Stationery"},
    {"item": "Headphones", "price": 150, "quantity": 2, "category": "Electronics"},
    {"item": "Shoes", "price": 80, "quantity": 1, "category": "Clothing"},
    {"item": "Pen", "price": 5, "quantity": 10, "category": "Stationery"}
]

# Step 1: Write a function get_item_total(item) that takes a single dictionary (e.g. one cart item)and returns its total value: price * quantity.
def get_item_total(item):
    total_value = [c['price']*c['quantity'] for c in cart]
    return total_value

# Step 2: Write a function get_cart_total(cart) that returns the total cost for the entire cart (using get_item_total() inside it).
def get_cart_total(cart_total):
    item_totals = get_item_total(cart_total)
    return(sum(item_totals))

# Step 3: Write a function get_category_totals(cart) that returns a dictionary of total spend per category, e.g.:
def get_category_totals(cart_spend):
    spend_dict = {}
    for c in cart_spend:
        for k,v in c:
            spend_dict[k] = c.get(k,0) + v
    return spend_dict
get_category_totals(cart)

# Step 4: Write a function apply_discount(cart, threshold, discount_rate) that applies a discount to any item total that exceeds threshold. Return a new list with updated totals.

# Step 5 (Bonus 🔀): Write a cart_summary(cart) function that prints:
# Cart total: $1675.00
# Category totals: {'Electronics': 1500, 'Stationery': 95, 'Clothing': 80}
# Discounted cart total (if applicable): $1600.00

ValueError: too many values to unpack (expected 2)

In [140]:
# You’ll create these functions (each one small and focused):
# 1.	get_sum(numbers)
# 2.	get_average(numbers)
# 3.	get_max_min(numbers) → Returns both the max and min as a tuple (max, min).
# 4.	get_above_average(numbers) → Returns a new list of numbers greater than the average.
# 5.	Bonus 🔀:Create a function summary_report(numbers) that calls all the above functions and prints a clean summary like:

data = [2, 5, 8, 12, 14, 20]

def get_sum(numbers):
    return sum(numbers)

def get_average(numbers):
    return get_sum(numbers)/len(numbers)

def get_max_min(numbers):
    return((max(numbers), min(numbers)))

def get_above_average(numbers):
    avg_numbers = get_average(numbers)
    above_avg = [x for x in numbers if x > avg_numbers]
    return above_avg

def summary_report(numbers):
    output = f"""Total: {get_sum(numbers)}
Average: {get_average(numbers):.2f}
Max: {max(numbers)}
Min: {min(numbers)}
Above average: {get_above_average(numbers)}
"""
    return output
print(summary_report(data))

# Total: 55
# Average: 11.0
# Max: 20
# Min: 2
# Above average: [12, 14, 20]

Total: 61
Average: 10.17
Max: 20
Min: 2
Above average: [12, 14, 20]

In [ ]:
# Step 1: Import the random module and generate a random integer between 1 and 50. Store it in a variable called secret_number.
import random

secret_number = random.randint(1, 50)              # number between 1 and 50, inclusive

# Step 2: Set a variable called attempts to 5 — the user only gets five guesses.
attempts = 5

# Step 3: Use a loop to ask the user to guess a number. After each guess:
# 	•	If the guess is too high, print "Too high!"
# 	•	If it’s too low, print "Too low!"
# 	•	If it’s correct, print "Correct! You win!" and break the loop.

# Step 4: If the user runs out of attempts, print: Sorry, you ran out of attempts. The number was X.

# Step 5 (Bonus 🔀): After the game ends, ask if the user wants to play again. If they type "yes", restart the game; otherwise, print "Thanks for playing!".

# I'm thinking of a number between 1 and 50.
# You have 5 attempts to guess it.

# Enter your guess: 25
# Too low!
# Enter your guess: 40
# Too high!
# Enter your guess: 33
# Correct! You win!

In [ ]:
# Word Counter: You’ll write a small Python program that analyzes a user-provided sentence. The program should report key text statistics.

# Step 1: Ask the user to input a sentence using input() and store it in a variable called text.
# text = input('enter a sentence')
text = 'The quick, brown fox jumped, jumped over the lazy dog.'

# Step 2: Clean the sentence — remove punctuation like commas, periods, and exclamation marks.
# 💡 Hint: you can use .replace() or a comprehension.
import re
cleaned = re.sub(r'[^\w\s]', '', text)
cleaned
 
# # Step 3: Split the cleaned sentence into individual words (hint: .split()).
clean_split = [t.lower() for t in cleaned.split()] 

# # Step 4: Compute and print the following:
# # 	•	The total number of words
word_total = len(clean_split)

# # 	•	The number of unique words
unique_words = len(set(clean_split))

# # 	•	The longest word in the sentence
longest = max(clean_split, key=len)

# # Step 5 (Bonus 🔀): Use a dictionary to count how many times each word appears, then print a summary:
output = {}
for c in clean_split:
    output[c] = output.get(c,0) + 1


# Step 6: Sort the word frequencies so that the most common words appear first.
# output
sort_freq = {k: v for k, v in sorted(output.items(), key=lambda item: item[1], reverse=True)}

# Step 7: Remove stopwords
stopwords = ['the', 'and', 'a', 'of', 'in', 'to', 'is', 'it', 'on', 'for', 'with']
remove_stop = {k:v for k,v in output.items() if k not in stopwords}

{'quick': 1, 'brown': 1, 'fox': 1, 'jumped': 2, 'over': 1, 'lazy': 1, 'dog': 1}

In [ ]:
sales = [
    {"product": "Laptop", "category": "Electronics", "price": 1200, "quantity": 3, "region": "North"},
    {"product": "Book", "category": "Stationery", "price": 25, "quantity": 20, "region": "South"},
    {"product": "Headphones", "category": "Electronics", "price": 150, "quantity": 10, "region": "West"},
    {"product": "Shoes", "category": "Clothing", "price": 80, "quantity": 12, "region": "North"},
    {"product": "Shirt", "category": "Clothing", "price": 40, "quantity": 15, "region": "East"},
    {"product": "Pen", "category": "Stationery", "price": 5, "quantity": 50, "region": "West"},
    {"product": "Tablet", "category": "Electronics", "price": 600, "quantity": 5, "region": "South"},
    {"product": "Jacket", "category": "Clothing", "price": 120, "quantity": 7, "region": "North"}
]

# Step 1:
# Compute a new field revenue for each product (price * quantity).
for s in sales:
    s['revenue'] = s['price']*s['quantity']
 
# Step 2:
# Build a dictionary of total revenue by category.

cat_list = [s['category'] for s in sales]
rev_list = [s['revenue'] for s in sales]
cat_rev_tup = list(zip(cat_list, rev_list))
cat_rev_tup

cat_rev_dict = {}

for k,v in cat_rev_tup:
    cat_rev_dict[k] = cat_rev_dict.get(k,0) + v

    
# Step 3:
# Build a dictionary of total revenue by region.
region_list = [s['region'] for s in sales]
reg_rev_tup = list(zip(region_list, rev_list))

reg_rev_dict = {}

for k,v in reg_rev_tup:
    reg_rev_dict[k] = reg_rev_dict.get(k,0) + v 

# Step 4:
# Find the top-selling product (highest revenue).
prod_list = [s['product'] for s in sales]
prod_rev_dict = dict(zip(prod_list, rev_list))
highest = max(prod_rev_dict, key=prod_rev_dict.get)

# Step 5:
# Create a list of products labeled as "High" if their revenue ≥ 1000, else "Low".
# → Format: [("Laptop", "High"), ("Pen", "Low"), ...]
rev_cat_list = ['High' if x >= 1000 else 'Low' for x in rev_list]
prod_cat_list = list(zip(prod_list, rev_cat_list))

# Step 6 (Bonus Twist 🔀):
# Use a list comprehension to get the names of all products in the "Electronics" category
# whose revenue is above the average revenue across all products.
avg_rev = sum(rev_list) / len(rev_list)

prod_above_avg = [s['product'] for s in sales if s['revenue'] > avg_rev and s['category'] == 'Electronics']

['Laptop', 'Headphones', 'Tablet']

In [ ]:
students = [
    {"name": "Alice", "subject": "Math", "score": 88},
    {"name": "Bob", "subject": "Math", "score": 75},
    {"name": "Charlie", "subject": "History", "score": 92},
    {"name": "Diana", "subject": "History", "score": 81},
    {"name": "Evan", "subject": "Science", "score": 95},
    {"name": "Fiona", "subject": "Science", "score": 89},
    {"name": "George", "subject": "Math", "score": 94},
    {"name": "Hannah", "subject": "Science", "score": 76},
]

# 1.	Create a set of unique subjects.
uniq_subj = {s['subject'] for s in students}

# 2.	Build a dictionary showing the total score per subject.
subj_list = [s['subject'] for s in students]
score_list = [s['score'] for s in students]

subj_score_tup = list(zip(subj_list, score_list))
subj_score_dict = {}
for k,v in subj_score_tup:
    subj_score_dict[k] = subj_score_dict.get(k,0) + v

# 3.	Build another dictionary for the average score per subject.

subj_count_dict = {}
for k,v in subj_score_tup:
    subj_count_dict[k] = subj_count_dict.get(k,0) + 1

subj_count_dict
all_keys = subj_score_dict.keys() | subj_count_dict.keys()

output = {}
for key in all_keys: 
    output[key] = subj_score_dict[key] / subj_count_dict[key] 

# 4.	Find the subject with the highest average score.
high_subj = max(output, key=output.get)

# 5.	Extra twist 🔀: Create a list comprehension that returns the names of all students
# whose score is above the overall average score across all students.

stu_avg = sum(score_list) / len(score_list)
name_list = [s['name'] for s in students]
stu_scores_dict = dict(zip(name_list, score_list))

stu_list = [k for k,v in stu_scores_dict.items() if v > stu_avg]

86.25

In [ ]:
sales = [
    {"product": "Laptop", "category": "Electronics", "price": 1200, "quantity": 3},
    {"product": "Book", "category": "Stationery", "price": 20, "quantity": 15},
    {"product": "Headphones", "category": "Electronics", "price": 150, "quantity": 5},
    {"product": "Shoes", "category": "Clothing", "price": 80, "quantity": 8},
    {"product": "Shirt", "category": "Clothing", "price": 40, "quantity": 10},
    {"product": "Pen", "category": "Stationery", "price": 5, "quantity": 30}
]

# 1.	Create a set of unique categories.
cat_set = {s['category'] for s in sales}

# 2.	Build a dictionary showing total revenue per category (price * quantity).
rev_list = [s['price']*s['quantity'] for s in sales]
cat_list = [s['category'] for s in sales]

rev_tup = list(zip(cat_list, rev_list))
rev_dict = {}
for k,v in rev_tup:
    rev_dict[k] = rev_dict.get(k,0) + v
 

# 3.	Build another dictionary showing total quantity sold per category.
quant_list = [s['quantity'] for s in sales]
quant_tup = list(zip(cat_list, quant_list))
quant_dict = {}

for k,v in quant_tup:
    quant_dict[k] = quant_dict.get(k,0) + v

# 4.	Find the category with the highest total revenue.
highest_rev = max(rev_dict, key=rev_dict.get)

# 5.	Extra twist 🔀: Create a list comprehension that returns the names of all products
# whose revenue is above the average revenue across all products.

avg_rev = sum(rev_list) / len(rev_list)
product_list = [s['product'] for s in sales]

prod_rev = dict(zip(product_list, rev_list))
gt_avg_list = [k for k,v in prod_rev.items() if v > avg_rev]

{'Laptop': 3600,
 'Book': 300,
 'Headphones': 750,
 'Shoes': 640,
 'Shirt': 400,
 'Pen': 150}

In [ ]:
employees = [
    {"name": "Alice", "department": "IT", "salary": 72000, "years_at_company": 5},
    {"name": "Bob", "department": "Finance", "salary": 65000, "years_at_company": 2},
    {"name": "Charlie", "department": "IT", "salary": 80000, "years_at_company": 6},
    {"name": "Diana", "department": "HR", "salary": 60000, "years_at_company": 3},
    {"name": "Evan", "department": "Finance", "salary": 68000, "years_at_company": 4},
    {"name": "Fiona", "department": "IT", "salary": 75000, "years_at_company": 7}
]

# 1.	Create a list of unique departments.
unique_depts = {e['department'] for e in employees}

# 2.	Build a dictionary showing the total salary per department.
dept = [e['department'] for e in employees]
salary = [e['salary'] for e in employees] 

salary_tup = list(zip(dept, salary))

salary_dict = {}
for k,v in salary_tup:
    salary_dict[k] = salary_dict.get(k,0) + v 
 

# 3.	Build another dictionary for the average years at company per department.
years = [e['years_at_company'] for e in employees]

years_tup = list(zip(dept, years))

years_dict = {}
dept_count_dict = {}
for k,v in years_tup:
    years_dict[k] = years_dict.get(k,0) + v 
    dept_count_dict[k] = dept_count_dict.get(k,0) + 1

# dept_count_dict
output = {}
all_keys = years_dict.keys() | dept_count_dict.keys()
all_keys
for key in all_keys:
    output[key] = years_dict[key] / dept_count_dict[key]

# 4.	Find the department with the highest total salary.
highest = max(salary_dict, key=salary_dict.get)

# 5.	Extra twist 🔀: Use a list comprehension to create a list of departments where
# the average salary (total salary / employee count) is above 70,000.

new_list = [k for k in salary_dict.keys() if salary_dict[k]/dept_count_dict[k] > 70000]
new_list

['IT']

In [ ]:
employees = [
    {"name": "Alice", "department": "IT", "salary": 72000, "years_at_company": 5},
    {"name": "Bob", "department": "Finance", "salary": 65000, "years_at_company": 2},
    {"name": "Charlie", "department": "IT", "salary": 80000, "years_at_company": 6},
    {"name": "Diana", "department": "HR", "salary": 60000, "years_at_company": 3},
    {"name": "Evan", "department": "Finance", "salary": 68000, "years_at_company": 4},
    {"name": "Fiona", "department": "IT", "salary": 75000, "years_at_company": 7}
]

# 1.	Create a list of all employee names.
names = [e['name'] for e in employees]

# 2.	Create a set of all unique departments.
unique_depts = {e['department'] for e in employees}

# 3.	Compute a list of total compensation for each employee, defined as salary + (1000 * years_at_company).
total_comp = [(e['salary'] + e['years_at_company']*1000) for e in employees]

# 4.	Build a dictionary mapping each employee’s name to their total compensation.
comp_dict = dict(zip(names, total_comp))

# 5.	Find the employee with the highest total compensation.
highest = max(comp_dict, key=comp_dict.get)
# 6.	Extra twist 🔀: Use a list comprehension to create a new list of bonus amounts —
# employees in the "IT" department get a 10% bonus (salary * 0.10),
# everyone else gets 5% (salary * 0.05).
bonus = [e['salary']*(0.10) if e['department'] == 'IT' else e['salary']*(0.05) for e in employees]

[7200.0, 3250.0, 8000.0, 3000.0, 3400.0, 7500.0]

In [ ]:
sales = [
    {"product": "Laptop", "category": "Electronics", "price": 1200, "quantity": 3},
    {"product": "Book", "category": "Stationery", "price": 20, "quantity": 10},
    {"product": "Headphones", "category": "Electronics", "price": 150, "quantity": 5},
    {"product": "Shoes", "category": "Clothing", "price": 80, "quantity": 6},
    {"product": "Shirt", "category": "Clothing", "price": 40, "quantity": 8},
    {"product": "Pen", "category": "Stationery", "price": 5, "quantity": 20}
]

# 1.	Create a list of all product names.
products = [s['product'] for s in sales]

# 2.	Compute a new list of total revenue for each product (price * quantity).
revenue = [s['price'] * s['quantity'] for s in sales]

# 3.	Create a dictionary mapping each product to its total revenue.
product_dict = dict(zip(products, revenue))

# 4.	Find the product with the highest total revenue.
highest = max(product_dict, key=product_dict.get)
 
# 5.	Build a list of tuples (product, "High"/"Low") where "High" = revenue ≥ 500.
tup_category = ['High' if x >= 500 else 'Low' for x in product_dict.values()]
tup_list = list(zip(products, tup_category))
 
# 6.	Extra twist 🔀:Use a list comprehension to create a new list of discounted prices
# — apply a 10% discount (price * 0.9) only to products in the "Electronics" category.

discount_price = [p['price']*0.9 if p['category'] == 'Electronics' else p['price'] for p in sales]

[1080.0, 20, 135.0, 80, 40, 5]

In [579]:
movies = [
    {"title": "Inception", "genre": "Sci-Fi", "rating": 8.8},
    {"title": "The Godfather", "genre": "Crime", "rating": 9.2},
    {"title": "Interstellar", "genre": "Sci-Fi", "rating": 8.6},
    {"title": "The Dark Knight", "genre": "Action", "rating": 9.0},
    {"title": "Pulp Fiction", "genre": "Crime", "rating": 8.9},
    {"title": "The Matrix", "genre": "Sci-Fi", "rating": 8.7}
]

# 1.	Create a list of all movie titles.
titles = [m['title'] for m in movies]

# 2.	Get a set of all unique genres.
genre_set = {m['genre'] for m in movies}
# 3.	Find the highest-rated movie.
ratings = [m['rating'] for m in movies]
ratings_dict = dict(zip(titles, ratings))

highest = max(ratings_dict, key=ratings_dict.get) 

# 4.	Create a list of all movies with rating ≥ 9.0.
high_rating = [k for k,v in ratings_dict.items() if v >= 9.0]

# 5.	Build a list of tuples (title, "Top"/"Average") where "Top" = rating ≥ 9.0.
rating_cat = ['Top' if r >= 9 else 'Average' for r in ratings]
tup_list = list(zip(titles, rating_cat))

# 6.	Extra twist 🔀: Use a list comprehension to get only the movies in the “Sci-Fi” genre with rating ≥ 8.7.
[m['title'] for m in movies if m['genre'] == 'Sci-Fi' and m['rating'] >= 8.7]

['Inception', 'The Matrix']

In [571]:
products = [
    {"name": "Laptop", "category": "Electronics", "price": 1200},
    {"name": "Book", "category": "Stationery", "price": 25},
    {"name": "Headphones", "category": "Electronics", "price": 150},
    {"name": "Shoes", "category": "Clothing", "price": 80},
    {"name": "Shirt", "category": "Clothing", "price": 40},
    {"name": "Pen", "category": "Stationery", "price": 5}
]

# 1.	Create a list of all product names.
product_names = [p['name'] for p in products]

# 2.	Get a set of all unique categories.
product_cats = set([p['category'] for p in products])

# 3.	Find the most expensive product.
product_price = [p['price'] for p in products]
expensive_dict = dict(zip(product_names, product_price))

expensive = max(expensive_dict, key=expensive_dict.get)
 
# 4.	Create a list of products priced above 100.
gt_100 = [k for k,v in expensive_dict.items() if v > 100]

# 5.	Build a list of tuples (name, "Expensive"/"Cheap") where "Expensive" = price ≥ 100.
products_cat = ['Expensive' if v >= 100 else 'Cheap' for v in expensive_dict.values()]
tup_list = list(zip(product_names, products_cat))

# 6.	Extra twist 🔀: Use a list comprehension to get only the products in the "Electronics" category that cost less than 200.
twist_list = [p['name'] for p in products if p['category'] == 'Electronics' and p['price'] < 200]
twist_list

['Headphones']

In [ ]:
employees = [
    {"name": "Alice", "department": "IT", "salary": 72000},
    {"name": "Bob", "department": "Finance", "salary": 65000},
    {"name": "Charlie", "department": "IT", "salary": 80000},
    {"name": "Diana", "department": "HR", "salary": 60000},
    {"name": "Evan", "department": "Finance", "salary": 68000},
    {"name": "Fiona", "department": "IT", "salary": 75000}
]

# 6.	Extra twist 🔀: Use a list comprehension to get only the names of employees who work in IT and have a salary ≥ 75,000.
n_list = [[emp['name'],emp['department'], emp['salary']] for emp in employees] 

[l[0] for l in n_list if l[1] == 'IT' and l[2] >= 75000]

# 1.	Create a list of all employee names.
names = [v for emp in employees for k,v in emp.items() if k == 'name']
 
# 2.	Create a list of all unique departments.
depts = [v for emp in employees for k,v in emp.items() if k == 'department']
unique_depts = list(set(depts))

# 3.	Find the employee with the highest salary.
salary_dict = {}
for emp in employees:
    vals_list = list(emp.values())
    name_value = vals_list[0]
    salary_value = vals_list[-1]
    salary_dict[name_value] = salary_value

highest = max(salary_dict, key=salary_dict.get)

# 4.	Create a list of employees with salary ≥ 70,000.
highly_paid = []
for k,v in salary_dict.items():
    if v >= 70000:
        highly_paid.append(k)

# 5.	Build a list of tuples (name, "High"/"Low") where "High" = salary ≥ 70,000, else "Low".
salary_cat = ['High' if s >= 70000 else 'Low' for s in salary_dict.values()]
tup_list = list(zip(names, salary_cat))

['Charlie', 'Fiona']

In [ ]:
products = {
    "Laptop": {"price": 1200, "quantity": 5},
    "Book": {"price": 25, "quantity": 12},
    "Shirt": {"price": 40, "quantity": 8},
    "Shoes": {"price": 80, "quantity": 3},
    "Headphones": {"price": 150, "quantity": 7},
}

# 1.	Compute the total value of stock for each product (price * quantity), storing results in a new dictionary.
# 👉 Example: {"Laptop": 6000, "Book": 300, ...}

output_dict = {}

for o_key,o_val in products.items():
    tot_val = 1
    for i_key,i_val in o_val.items():
        tot_val *= i_val
    output_dict[o_key] = tot_val

# simplified --> output_dict = {k: v['price'] * v['quantity'] for k,v in products.items()}    

# 2.	Find the product with the highest stock value.
max_val = max(output_dict, key=output_dict.get)
 
# 3.	Create a list of tuples (product, "Low"/"High") where stock value ≥ 1000 → "High", else "Low".
product_cat = ['High' if x >= 1000 else 'Low' for x in output_dict.values()]
output_tup = list(zip(products, product_cat))

# 4.	Build a set of all unique prices.
prices = []
for o_key,o_val in products.items():
    for i_key,i_val in o_val.items():
        if i_key == 'price':
            prices.append(i_val)

unique_prices = set(prices)

# 5.	Compute the grand total stock value across all products.
total_value = sum(output_dict.values())

7910

In [ ]:
products = ["Laptop", "Book", "Shirt", "Shoes", "Headphones"]
quantities = [5, 12, 8, 3, 7]

# 1.	Create a dictionary mapping each product to its quantity.
# 👉 {"Laptop": 5, "Book": 12, ...}
dict_map = dict(zip(products, quantities))

# 2.	Find the product with the lowest quantity.
lowest = min(dict_map, key=dict_map.get)

# 3.	Create a list of products that have quantity ≥ 7.
gt_7 = []

for k,v in dict_map.items():
    if v >= 7:
        gt_7.append(k)

# gt_7 = [k for k,v in dict_map.items() if v >= 7] ==> solution as list comprehension

# 4.	Build a set of all unique quantities.
unique_q = set(quantities)

# 5.	Create a list of tuples where each tuple is (product, "Low"/"High") — label “High” if quantity ≥ 7, else “Low”.
# 👉 Example: [("Laptop", "Low"), ("Book", "High"), ...]

hl_cat = ['High' if val >= 7 else 'Low' for val in dict_map.values()]
tup_list = list(zip(products, hl_cat))

['Book', 'Shirt', 'Headphones']

In [ ]:
students = ["Alice", "Bob", "Charlie", "Diana", "Evan"]
scores = [85, 92, 78, 88, 95]

# 1.	Create a dictionary mapping each student to their score.
# 👉 {"Alice": 85, "Bob": 92, ...}
map_dict = dict(zip(students, scores))

# 2.	Find the highest score and the student who earned it.
highest = max(map_dict, key=map_dict.get)
highest 

# 3.	Compute the average score (integer or float is fine).
sum_score = 0
count_score = 0

for v in map_dict.values():
    sum_score += v 
    count_score += 1

avg_score = sum_score / count_score

# 4.	Create a set of all scores greater than 90.
gt_90 = []
for val in map_dict.values():
    if val > 90:
        gt_90.append(val)

# 5.	Create a list of tuples where each tuple is (student, pass/fail) — passing if score ≥ 80, else failing.
# 👉 Example: [("Alice", "Pass"), ("Charlie", "Fail"), ...]
vals = ['Pass' if v >= 80 else 'Fail' for v in map_dict.values()]
pf_tup = list(zip(students, vals))

[('Alice', 'Pass'),
 ('Bob', 'Pass'),
 ('Charlie', 'Fail'),
 ('Diana', 'Pass'),
 ('Evan', 'Pass')]

In [ ]:
employees = ["Alice", "Bob", "Charlie", "Diana", "Evan"]
departments = ["IT", "Finance", "IT", "HR", "Finance"]

# 1.	Combine the two lists into a dictionary where each employee is the key and their department is the value.
# 👉 Example: {"Alice": "IT", "Bob": "Finance", ...}
my_dict = dict(zip(employees, departments))
# my_dict 

# 2.	Get the set of unique departments.
unique_dept = set(departments)

# 3.	Count how many employees work in each department, and store in a dictionary.
# 👉 Example: {"IT": 2, "Finance": 2, "HR": 1}
output = {}

for d in departments:
    output[d] = output.get(d, 0) + 1
# output     

# 4.	Create a list of tuples pairing each employee with their department.
# 👉 Example: [("Alice", "IT"), ("Bob", "Finance"), ...]
my_tup = list(zip(employees, departments))
# my_tup

[('Alice', 'IT'),
 ('Bob', 'Finance'),
 ('Charlie', 'IT'),
 ('Diana', 'HR'),
 ('Evan', 'Finance')]

In [ ]:
.............incomplete, unfinished

products = [
    ("Laptop", 1200),
    ("Book", 25),
    ("Shirt", 40),
    ("Shoes", 80),
    ("Headphones", 150)
]

sales = [
    {"customer": "Alice", "product": "Laptop", "quantity": 1},
    {"customer": "Bob", "product": "Book", "quantity": 3},
    {"customer": "Charlie", "product": "Shoes", "quantity": 2},
    {"customer": "Alice", "product": "Shirt", "quantity": 1},
    {"customer": "Diana", "product": "Laptop", "quantity": 2},
    {"customer": "Evan", "product": "Headphones", "quantity": 1},
    {"customer": "Bob", "product": "Shirt", "quantity": 2},
]

# 1.	Convert products (a list of tuples) into a dictionary where keys = product names, values = prices.
my_dict = dict(products) 

# 2.	Using that dictionary, compute the total spend per customer from the sales list (dictionary lookups required).
# 3.	Store results in a new list of tuples, sorted by total spend descending.
# 👉 Example: [("Diana", 2400), ("Alice", 1240), ...]
# 4.	Get the set of unique products purchased across all sales.
# 5.	Use a tuple unpacking trick to loop through products and print them in the form:
# "Product: Laptop, Price: 1200"

{'Laptop': 1200, 'Book': 25, 'Shirt': 40, 'Shoes': 80, 'Headphones': 150}

In [ ]:

import pandas as pd

orders = pd.DataFrame({
    "order_id": [201, 202, 203, 204, 205, 206, 207],
    "customer": ["Alice", "Bob", "Charlie", "Alice", "Diana", "Charlie", "Bob"],
    "product": ["Book", "Laptop", "Shirt", "Shoes", "Laptop", "Book", "Shoes"],
    "price": [20, 900, 40, 60, 850, 25, 65],
    "quantity": [2, 1, 3, 1, 1, 2, 1],
    "order_date": pd.to_datetime([
        "2024-02-01","2024-02-02","2024-02-02",
        "2024-02-03","2024-02-03","2024-02-04","2024-02-04"
    ])
})

# 1.	Compute order_value = price * quantity.
orders['order_value'] = orders['price'] * orders['quantity']

# 2.	Find the total revenue per product.
prod_rev = orders.groupby('product', as_index=False).agg(product_rev=('order_value', 'sum'))

# 3.	Which customer placed the most orders?
o_count = orders.groupby('customer', as_index=False).agg(order_count=('order_id', 'count'))
o_count['rank'] = o_count['order_count'].rank(ascending=False, method='min')
max_orders = o_count[o_count['rank'] == 1] 

df = o_count.sort_values(by=['order_count', 'customer'], ascending=False).iloc[0]

# 4.	For each day, calculate the total quantity of items sold.
total_quantity = orders.groupby('order_date', as_index=False).agg(total_quant=('quantity', 'sum')).sort_values(by='order_date')

# 5.	Use a list comprehension to add a column weekday with the day name (e.g. "Monday") from order_date.
orders['weekday'] = orders['order_date'].dt.day_name()

# 6.	Identify customers who spent over 1000 in total revenue.
customer_spend = orders.groupby('customer', as_index=False).agg(cust_spend=('order_value', 'sum'))
customer_1000 = customer_spend[customer_spend['cust_spend'] > 1000]

# 7.	Bonus: Compute a running cumulative revenue across all orders sorted by date.
orders['cum_sum'] = orders.sort_values(by='order_date')['order_value'].cumsum()

,order_id,customer,product,price,quantity,order_date,order_value,weekday,cum_sum
0,201,Alice,Book,20,2,2024-02-01,40,Thursday,40
1,202,Bob,Laptop,900,1,2024-02-02,900,Friday,940
2,203,Charlie,Shirt,40,3,2024-02-02,120,Friday,1060
3,204,Alice,Shoes,60,1,2024-02-03,60,Saturday,1120
4,205,Diana,Laptop,850,1,2024-02-03,850,Saturday,1970
5,206,Charlie,Book,25,2,2024-02-04,50,Sunday,2020
6,207,Bob,Shoes,65,1,2024-02-04,65,Sunday,2085

In [ ]:
"""
	1.	Compute order_value = price * quantity.
	2.	Find the total revenue per customer.
	3.	Which product generated the highest total revenue?
	4.	For each day, compute the average order value.
	5.	Use a list comprehension to create a column high_value = True if order_value > 500, else False.
	6.	Find customers who bought more than one distinct product.
	7.	Bonus: Compute a running cumulative revenue per customer over time.
"""

import pandas as pd

sales = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106],
    "customer": ["Alice", "Bob", "Alice", "Diana", "Charlie", "Bob"],
    "product": ["Laptop", "Book", "Shirt", "Laptop", "Shoes", "Shirt"],
    "price": [1200, 20, 35, 1100, 80, 40],
    "quantity": [1, 2, 3, 1, 1, 2],
    "order_date": pd.to_datetime([
        "2024-01-05","2024-01-06","2024-01-06",
        "2024-01-07","2024-01-07","2024-01-08"
    ])
})

sales['order_value'] = sales['price'] * sales['quantity']

cust_rev = sales.groupby('customer', as_index=False).agg(cust_revenue=('order_value', 'sum'))

top_product = sales.groupby('product', as_index=False).agg(prod_revenue=('order_value', 'sum')).nlargest(1, 'prod_revenue')

daily_aov = sales.groupby('order_date', as_index=False).agg(aov=('order_value', 'mean'))

sales['high_value'] = [x > 500 for x in sales['order_value']]

gt1_prod = sales.groupby('customer', as_index=False).agg(product_count=('product','nunique'))
gt1_prod[gt1_prod['product_count'] > 1]

sales = sales.sort_values(by=['customer','order_date'], ascending=True)
sales['cum_sum'] = sales.groupby('customer', as_index=False)['order_value'].cumsum()
sales

,order_id,customer,product,price,quantity,order_date,order_value,high_volume,cum_sum
0,101,Alice,Laptop,1200,1,2024-01-05,1200,True,1200
1,102,Bob,Book,20,2,2024-01-06,40,False,40
2,103,Alice,Shirt,35,3,2024-01-06,105,False,1305
3,104,Diana,Laptop,1100,1,2024-01-07,1100,True,1100
4,105,Charlie,Shoes,80,1,2024-01-07,80,False,80
5,106,Bob,Shirt,40,2,2024-01-08,80,False,120

In [350]:
import pandas as pd

# Sample DataFrame
data = {'col1': [1, 2, 3, 4, 5],
        'col2': ['A', 'B', 'C', 'D', 'E']}
df = pd.DataFrame(data)

# List of values to filter by
filter_list = [2, 4]

# Create a boolean Series using a list comprehension
# This checks if each value in 'col1' is present in filter_list
boolean_series = pd.Series([val in filter_list for val in df['col1']])
boolean_series
# Filter the DataFrame using the boolean Series
# filtered_df_lc = df[boolean_series]

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [361]:
"""	
	
"""

import pandas as pd

reviews = pd.DataFrame({
    "review_id": [1, 2, 3, 4, 5, 6],
    "customer": ["Alice", "Bob", "Charlie", "Diana", "Evan", "Fiona"],
    "review_text": [
        "Great laptop, battery life is amazing!",
        "Book was boring and slow.",
        "Shirt fits perfectly, love the color.",
        "Headphones are too expensive for the quality.",
        "Shoes are comfy, but delivery was late.",
        "Pen works fine, nothing special."
    ],
    "rating": [5, 2, 4, 3, 4, 3]
})
# 1.	Use a list comprehension to count the number of words in each review_text. Store in a new column word_count.
reviews['word_count'] = [len(x.split()) for x in reviews['review_text']]

# 2.	Extract the first word of each review (via list comp) into a new column first_word.
reviews['first_word'] = [x.split()[0] for x in reviews['review_text']]

# 3.	Find the average word count per rating.
avg_word_count = reviews.groupby('rating').agg(avg_word_count=('word_count', 'mean'))


# 4.	Identify reviews that mention “laptop” or “book” (case-insensitive). Return review_id + customer.
reviews['clean_text'] = reviews['review_text'].str.replace('[^a-zA-Z0-9]', ' ', regex=True).str.lower().str.split()
words = ['laptop', 'book']

reviews['mentions_laptop_or_book'] = [
    any(w in tokens for w in words) 
    for tokens in reviews['clean_text']
]

# 5.	Create a new column sentiment = "positive" if rating ≥4 else "negative".
reviews['sentiment'] = ['positive' if r >= 4 else 'negative' for r in reviews['rating']]

# 6.	Bonus: Use a list comprehension to get the length of each review’s longest word.
reviews['longest_length'] = [max(i, key=len) for x in reviews['clean_text'] for i in x]

reviews

ValueError: Length of values (36) does not match length of index (6)

In [ ]:
import pandas as pd

employees = pd.DataFrame({
    "emp_id": [1,2,3,4,5],
    "name": ["Alice","Bob","Charlie","Diana","Evan"],
    "department": ["IT","Finance","IT","HR","Finance"],
    "hire_date": pd.to_datetime(["2020-01-15","2019-03-10","2021-07-01","2018-06-12","2022-02-05"])
})

projects = pd.DataFrame({
    "proj_id": [101,102,103,104],
    "project": ["Migration","Audit","Website","Recruiting"],
    "department": ["IT","Finance","IT","HR"],
    "budget": [100000, 50000, 75000, 30000]
})

timesheets = pd.DataFrame({
    "emp_id": [1,1,2,3,3,4,5,5,5],
    "proj_id": [101,103,102,101,103,104,102,103,104],
    "hours": [120, 80, 150, 100, 60, 90, 50, 40, 30]
})

# 1.	Join employees ↔ timesheets ↔ projects into a single table.
merged_et = employees.merge(timesheets, how='inner', on='emp_id')
merged = merged_et.merge(projects, how='inner', on='proj_id', suffixes=('_left', '_right'))
merged.drop('department_right', axis='columns', inplace=True)
merged.rename(columns={'department_left': 'department'}, inplace=True)
# merged
# 2.	Compute total hours logged per employee.
emp_hours = merged.groupby(['emp_id', 'name', 'department'], as_index=False).agg(hours_logged=('hours', 'sum'))

# 3.	Find the top project by total hours (tie-safe).
project_hours = merged.groupby(['proj_id', 'project'], as_index=False).agg(proj_hours=('hours', 'sum'))
project_hours['hours_rank'] = project_hours['proj_hours'].rank(ascending=False, method='first') 
top_project = project_hours[project_hours['hours_rank'] == 1]
# top_project

# 4.	For each department, calculate the average project budget.
# avg_budget = merged.groupby('department', as_index=False).agg(avg_budget=('budget', 'mean'))
avg_budget = projects.groupby('department', as_index=False).agg(avg_budget=('budget', 'mean'))
# avg_budget

# 5.	List employees who worked on more than 1 project.
project_count = merged.groupby(['emp_id', 'name'], as_index=False).agg(proj_count=('proj_id', 'nunique'))
proj_emp_list = project_count[project_count['proj_count'] > 1].name.to_list()

# # 6.	Using a list comprehension, extract each employee’s hire year into a new column.
employees['hire_year'] = [int(x.split('-')[0]) for x in employees['hire_date'].astype(str)]


# 7.	Compute each employee’s % of total project hours within their department.
department_hrs = merged.groupby('department', as_index=False).agg(dept_hours=('hours', 'sum'))
dept_merge = emp_hours.merge(department_hrs, how='left', on='department')
dept_merge['dept_pct'] = dept_merge['hours_logged'] / dept_merge['dept_hours']

# # 8.	Bonus (window): for each project, rank employees by hours worked (dense rank).
merged['emp_proj_rank'] = merged.groupby(['project', 'proj_id', 'emp_id', 'name'], group_keys=False)['hours'].rank(ascending=False, method='dense')
merged.sort_values(by=['project', 'emp_proj_rank'])

,emp_id,name,department,hire_date,proj_id,hours,project,budget,emp_proj_rank
2,2,Bob,Finance,2019-03-10,102,150,Audit,50000,1.0
6,5,Evan,Finance,2022-02-05,102,50,Audit,50000,1.0
0,1,Alice,IT,2020-01-15,101,120,Migration,100000,1.0
3,3,Charlie,IT,2021-07-01,101,100,Migration,100000,1.0
5,4,Diana,HR,2018-06-12,104,90,Recruiting,30000,1.0
8,5,Evan,Finance,2022-02-05,104,30,Recruiting,30000,1.0
1,1,Alice,IT,2020-01-15,103,80,Website,75000,1.0
4,3,Charlie,IT,2021-07-01,103,60,Website,75000,1.0
7,5,Evan,Finance,2022-02-05,103,40,Website,75000,1.0

In [156]:
"""
	1.	Revenue per order: join orders → lines → products and compute order_value (sum of quantity*unit_price per order).
	2.	Monthly revenue: total revenue per calendar month (YYYY‑MM), sorted descending.
	3.	Top 2 products by revenue within each category (tie‑safe rank).
	4.	Customer LTV: total revenue per customer; list the top 3 customers by LTV with their first order date.
	5.	Average order value (AOV) by email domain (use a list comprehension to extract domain from email).
	6.	Repeat rate: percentage of customers with ≥2 orders.
	7.	Category mix per month: a pivot showing monthly revenue by category with a “Total” column.
	8.	Bonus (window): for each customer, compute a running cumulative revenue over time (by order_date).
"""
import pandas as pd

# Customers (emails useful for parsing domain via list comprehension)
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "name": ["Alice", "Bob", "Charlie", "Diana", "Evan"],
    "email": ["alice@gmail.com", "bob@yahoo.com", "charlie@company.com",
              "diana@gmail.com", "evan@outlook.com"],
    "signup_date": pd.to_datetime(["2024-01-01","2024-01-05","2024-01-10","2024-02-01","2024-02-05"])
})

# Products
products = pd.DataFrame({
    "product_id": [10, 20, 30, 40],
    "product": ["Laptop", "Book", "Shirt", "Headphones"],
    "category": ["Electronics", "Books", "Clothing", "Electronics"],
    "unit_price": [1200, 20, 35, 150]
})

# Orders (multiple per customer)
orders = pd.DataFrame({
    "order_id": [101,102,103,104,105,106,107,108,109],
    "customer_id": [1,1,2,3,3,4,4,4,5],
    "order_date": pd.to_datetime(["2024-02-03","2024-03-01","2024-02-10","2024-02-15","2024-03-02",
                                  "2024-02-20","2024-02-28","2024-03-05","2024-03-10"])
})

# Order lines (order can contain multiple products)
lines = pd.DataFrame({
    "order_id": [101,101,102,103,104,104,105,106,107,108,109,109],
    "product_id": [10,20,20,30,10,30,20,40,40,30,20,30],
    "quantity": [1,2,1,2,1,1,3,1,2,2,5,1]
})
# 1.	Revenue per order: join orders → lines → products and compute order_value (sum of quantity*unit_price per order).
merged_ol = orders.merge(lines, how='inner', on='order_id')
merged_olp = merged_ol.merge(products, how='inner', on='product_id')
merged_olp['order_value'] = merged_olp['quantity'] * merged_olp['unit_price']
# merged_olp.groupby('order_id', as_index=False).agg(rev_per_order=('order_value', 'sum'))

# 2.	Monthly revenue: total revenue per calendar month (YYYY‑MM), sorted descending.
merged_olp['order_month'] = merged_olp['order_date'].dt.to_period('M').astype(str)
monthly_rev = merged_olp.groupby('order_month', as_index=False).agg(total_revenue = ('order_value', 'sum')).sort_values(by='total_revenue', ascending=False)
# monthly_rev

# 3.	Top 2 products by revenue within each category (tie‑safe rank).
merged_olp['rank'] = merged_olp.groupby(['category'], group_keys=False)['order_value'].rank(ascending=False, method='first')
top_2 = merged_olp[merged_olp['rank'] >= 2]


# # 4.	Customer LTV: total revenue per customer; list the top 3 customers by LTV with their first order date.
merged = customers.merge(merged_olp, how='left', on='customer_id')
top_cust = (merged.groupby(['customer_id', 'name'], as_index=False)
            .agg(tot_rev=('order_value', 'sum'), first_order=('order_date', 'min'))
            .nlargest(3, 'tot_rev')
            )

# 5.	Average order value (AOV) by email domain (use a list comprehension to extract domain from email).

# get total for each order...then get average
merged['domain'] = [x.split('@')[-1] for x in merged['email']]
order_df = merged.groupby(['order_id', 'domain', 'customer_id', 'name', 'order_date'], as_index=False).agg(order_total=('order_value', 'sum'))
avg_order_value = order_df.groupby('domain', as_index=False).agg(avg_order_value=('order_total', 'mean'))


# 6.	Repeat rate: percentage of customers with ≥2 orders.
customer_totals = order_df.groupby(['customer_id', 'name'], as_index=False).agg(total_orders=('order_id', 'nunique'))
repeat_customers = len(customer_totals[customer_totals['total_orders'] >= 2])

repeat_raw = repeat_customers / merged['customer_id'].nunique()
repeat_percent = "{:.2%}".format(repeat_raw)
repeat_percent

# 7.	Category mix per month: a pivot showing monthly revenue by category with a “Total” column.
category_mix = pd.pivot_table(merged_olp, columns='category', index='order_month', values='order_value', aggfunc='sum', margins=True, margins_name='Total').fillna(0)

# # 8.	Bonus (window): for each customer, compute a running cumulative revenue over time (by order_date).
order_df = order_df.sort_values(by=['customer_id', 'order_date']).reset_index(drop=True)
order_df['cumulative_rev'] = order_df.groupby('customer_id')['order_total'].cumsum(axis=0)
order_df

/var/folders/wc/8wws1lfd3kv91ykflkc2lzxc0000gn/T/ipykernel_99694/486731380.py:88: FutureWarning: The 'axis' keyword in SeriesGroupBy.cumsum is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  order_df['cumulative_rev'] = order_df.groupby('customer_id')['order_total'].cumsum(axis=0)

,order_id,domain,customer_id,name,order_date,order_total,cumulative_rev
0,101,gmail.com,1,Alice,2024-02-03,1240,1240
1,102,gmail.com,1,Alice,2024-03-01,20,1260
2,103,yahoo.com,2,Bob,2024-02-10,70,70
3,104,company.com,3,Charlie,2024-02-15,1235,1235
4,105,company.com,3,Charlie,2024-03-02,60,1295
5,106,gmail.com,4,Diana,2024-02-20,150,150
6,107,gmail.com,4,Diana,2024-02-28,300,450
7,108,gmail.com,4,Diana,2024-03-05,70,520
8,109,outlook.com,5,Evan,2024-03-10,135,135

In [ ]:
"""
	1.	Average rating per movie (include count_ratings).
	2.	Top 2 movies per genre by average rating (tie ‑ safe).
	3.	Users with >2 ratings and their most recent rating (movie + rating + date).
	4.	List comprehension: extract the year from title into a new year column (ints), e.g., "Inception (2010)" → 2010.
"""
import pandas as pd

movies = pd.DataFrame({
    "movie_id": [1, 2, 3, 4, 5, 6],
    "title": ["Inception (2010)", "Toy Story (1995)", "The Matrix (1999)",
              "Inside Out (2015)", "Interstellar (2014)", "Coco (2017)"],
    "genre": ["Sci-Fi", "Animation", "Sci-Fi", "Animation", "Sci-Fi", "Animation"]
})

ratings = pd.DataFrame({
    "user_id": [10,10,11,11,12,12,12,13,13,14,14,15,15,15],
    "movie_id": [1,2,1,3,1,4,5,2,6,3,5,2,4,6],
    "rating": [5,4,4,5,5,4,4,5,5,4,5,3,5,4],
    "rated_at": pd.to_datetime([
        "2024-01-01","2024-01-03","2024-01-02","2024-01-04",
        "2024-01-05","2024-01-07","2024-01-08","2024-01-06","2024-01-09",
        "2024-01-10","2024-01-12","2024-01-11","2024-01-13","2024-01-14"
    ])
})

merged = movies.merge(ratings, how='inner', on='movie_id')
avg_ratings = merged.groupby(['movie_id', 'title', 'genre'], as_index=False).agg(avg_rating=('rating', 'mean'), rating_count=('rating', 'count'))

top_2 = avg_ratings.groupby('genre', group_keys=False).apply(lambda x: x.nlargest(2, 'avg_rating')).reset_index(drop=True)

vc = merged['user_id'].value_counts()
vc_df = vc[vc > 2].reset_index()
gt_2 = vc_df['user_id'].to_list()
users = merged[merged['user_id'].isin(gt_2)]
user_ratings = users.groupby(['user_id'], group_keys=False).apply(lambda x: x.nlargest(1, 'rated_at'))
user_ratings[['user_id', 'title', 'rating', 'rated_at']]


movies['release_year'] = [int(x.split()[-1].strip('()')) for x in movies['title']]
movies

/var/folders/wc/8wws1lfd3kv91ykflkc2lzxc0000gn/T/ipykernel_99694/354949598.py:34: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_2 = avg_ratings.groupby('genre', group_keys=False).apply(lambda x: x.nlargest(2, 'avg_rating')).reset_index(drop=True)
/var/folders/wc/8wws1lfd3kv91ykflkc2lzxc0000gn/T/ipykernel_99694/354949598.py:42: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_users = users.groupby(['user_id'], group_keys=False).apply(lambda x: x.nlargest(1, 'rated_at'))

   movie_id                title      genre  release_year
0         1     Inception (2010)     Sci-Fi          2010
1         2     Toy Story (1995)  Animation          1995
2         3    The Matrix (1999)     Sci-Fi          1999
3         4    Inside Out (2015)  Animation          2015
4         5  Interstellar (2014)     Sci-Fi          2014
5         6          Coco (2017)  Animation          2017

In [ ]:
"""
	1.	Left join customers ↔ orders so that customers with no orders still appear (orders columns as NaN).
	2.	Outer join orders ↔ products to flag product mismatches (e.g., product_id=99 not found).
	3.	Compute total spent per customer (quantity × unit_price), including zero for customers with no orders.
	4.	Compute revenue by category (use the products table), sorted descending.
	5.	List customers with no orders.
	6.	Find the largest single order value (quantity × unit_price), returning the customer, product, and amount.
	7.	Using the returns table, compute net revenue per customer = gross revenue − (returned_qty × unit_price).
	8.	Bonus: average order value per city, counting only customers with orders; then show a variant that lists all cities, with 0 where applicable.
"""
import pandas as pd

# Customers (note: Erin has no orders)
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "name": ["Alice", "Bob", "Charlie", "Diana", "Erin"],
    "city": ["New York", "Los Angeles", "Chicago", "New York", "Boston"]
})

# Orders (note: one order has a product_id not in products)
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107],
    "customer_id": [1, 2, 1, 3, 2, 4, 1],
    "product_id": [10, 20, 30, 20, 99, 10, 30],
    "quantity": [1, 1, 2, 1, 3, 1, 1]
})

# Products (note: no product_id=99 here)
products = pd.DataFrame({
    "product_id": [10, 20, 30, 40],
    "product": ["Laptop", "Book", "Shirt", "Headphones"],
    "unit_price": [1200, 20, 35, 150],
    "category": ["Electronics", "Books", "Clothing", "Electronics"]
})

# Optional: Returns (order-level returns to subtract from revenue)
returns = pd.DataFrame({
    "order_id": [103, 105],
    "returned_qty": [1, 1]
})

co_merged = customers.merge(orders, how='left', on='customer_id')
op_merged = orders.merge(products, how='outer', on='product_id', indicator=True)
mismatches = op_merged[op_merged['_merge'] != 'both']      # rows without a match
mismatches

merged = co_merged.merge(products, how='left', on='product_id')
merged['amount_spent'] = (merged['quantity'] * merged['unit_price']).fillna(0)

total_spent = merged.groupby('name', as_index=False).agg(total_spent=('amount_spent', 'sum'))

po_merged = products.merge(orders, how='left', on='product_id')
po_merged['revenue'] = po_merged['unit_price'] * po_merged['quantity']
product_revenue = po_merged.groupby('product', as_index=False).agg(product_rev=('revenue', 'sum')).sort_values('product_rev', ascending=False)

no_orders = co_merged[co_merged['order_id'].isnull()]

# 6.	Find the largest single order value (quantity × unit_price), returning the customer, product, and amount.
op_merged['order_value'] = op_merged['unit_price'] * op_merged['quantity']
largest_order = op_merged[['customer_id', 'product', 'order_value']].nlargest(1, 'order_value')

# 7.	Using the returns table, compute net revenue per customer = gross revenue − (returned_qty × unit_price).
df = merged.merge(returns, how='left', on='order_id')
df['return_amount'] = (df['returned_qty'] * df['unit_price']).fillna(0)
df['net_revenue'] = df['amount_spent'] - df['return_amount']
total_net = df.groupby('customer_id', as_index=False).agg(total_net=('net_revenue', 'sum'))
total_net
# 8.	Bonus: average order value per city, counting only customers with orders; then show a variant that lists all cities, with 0 where applicable.

aov_city_with_orders = merged[merged['amount_spent'] > 0].groupby('city', as_index=False).agg(aov_city=('amount_spent', 'mean'))
aov_city_all = merged.groupby('city', as_index=False).agg(aov_city=('amount_spent', 'mean'))

,order_id,customer_id,product_id,quantity,product,unit_price,category,_merge
6,NaN,NaN,40,NaN,Headphones,150.0,Electronics,right_only
7,105.0,2.0,99,3.0,NaN,NaN,NaN,left_only

In [ ]:
city	aov_city
0	Boston	0.00
1	Chicago	20.00
2	Los Angeles	10.00
3	New York	626.25

	city	aov_city
0	Chicago	20.00
1	Los Angeles	20.00
2	New York	626.25

In [ ]:
"""
	1.	Join customers and orders to get a single table with customer names, cities, and their orders.
	2.	Find the total amount spent per customer.
	3.	Find the average order amount per city.
	4.	List customers who have placed more than 1 order.
	5.	Which customer made the largest single purchase?
"""
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "Diana"],
    "city": ["New York", "Los Angeles", "Chicago", "New York"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106],
    "customer_id": [1, 2, 1, 3, 2, 4],
    "product": ["Laptop", "Book", "Shirt", "Shoes", "Pen", "Book"],
    "amount": [1200, 20, 35, 80, 5, 15]
})

merged = customers.merge(orders, how='inner', on='customer_id')
cust_spend = merged.groupby('name', as_index=False).agg(total_spent=('amount', 'sum'))
city_avg = merged.groupby('city', as_index=False).agg(avg_order=('amount', 'mean'))
gt_1 = (
    merged.groupby('name', as_index=False)
        .agg(order_count=('order_id', 'count'))
        .query('order_count > 1')['name']
        .to_list()
        )
largest_purch = merged.nlargest(1, 'amount')

   customer_id   name      city  order_id product  amount
0            1  Alice  New York       101  Laptop    1200

In [ ]:
"""
	1.	Compute the total revenue per product.
	2.	Find the best-selling category by total revenue.
	3.	Get a list of products that sold more than 100 units (use a list comprehension).
	4.	For each category, calculate the average price of products.
	5.	Identify the most expensive product overall.
"""
import pandas as pd

data = {
    "product_id": [1, 2, 3, 4, 5, 6],
    "product_name": ["Laptop", "Book", "Shirt", "Headphones", "Shoes", "Pen"],
    "category": ["Electronics", "Books", "Clothing", "Electronics", "Clothing", "Books"],
    "price": [1200, 20, 30, 150, 80, 2],
    "units_sold": [50, 200, 150, 75, 120, 500]
}

df = pd.DataFrame(data)

df['total_revenue'] = df['price'] * df['units_sold']
total_rev = df.groupby('product_name', as_index=False).agg(product_revenue=('total_revenue', 'sum'))

top_cat = (df.groupby('category', as_index=False)
 .agg(cat_revenue=('total_revenue', 'sum'))
 .sort_values(by='cat_revenue', ascending=False)
 .head(1)
)

gt_100 = [j for i, j in zip(df['units_sold'], df['product_name']) if i > 100]
avg_price = df.groupby('category', as_index=False).agg(avg_price=('price', 'mean'))
most_exp = df.nlargest(1, 'price')
most_exp

   product_id product_name     category  price  units_sold  total_revenue
0           1       Laptop  Electronics   1200          50          60000

In [ ]:
"""
	1.	Calculate the average score per student across all subjects.
	2.	List the names of students who scored above 90 in any subject (use a list comprehension).
	3.	Find the top student by average score.
	4.	For each subject, compute the highest score achieved.
	5.	Which students scored below 70 in at least one subject?
"""

import pandas as pd

data = {
    "student_id": [1, 2, 3, 4, 5, 6],
    "name": ["Alice", "Bob", "Charlie", "Diana", "Evan", "Fiona"],
    "math_score": [85, 92, 76, 88, 59, 95],
    "english_score": [78, 85, 67, 90, 72, 88],
    "science_score": [91, 89, 73, 85, 60, 94],
}

df = pd.DataFrame(data)

df['avg_score'] = df[['math_score', 'english_score', 'science_score']].mean(axis=1).round(1)

gt_90 = [n for m, e, s, n in zip(df['math_score'], df['english_score'], df['science_score'], df['name']) if (m > 90 or e > 90 or s > 90)]

top_student = df.nlargest(1, 'avg_score')

highest = df[['math_score', 'science_score', 'english_score']].max()

lt_70 = [n for m, e, s, n in zip(df['math_score'], df['english_score'], df['science_score'], df['name']) if (m < 70 or e < 70 or s < 70)]
lt_70

['Charlie', 'Evan']

In [ ]:
"""
	1.	Calculate the total revenue per customer.
	2.	Find the most frequently purchased product.
	3.	For each product, compute the average order value (price × quantity).
	4.	Which day had the highest total sales revenue?
	5.	Which customer bought the largest total quantity of items?
"""

import pandas as pd

data = {
    "order_id": [1, 2, 3, 4, 5, 6, 7],
    "customer": ["Alice", "Bob", "Alice", "Charlie", "Diana", "Bob", "Alice"],
    "product": ["Book", "Laptop", "Shirt", "Book", "Shirt", "Book", "Laptop"],
    "price": [20, 900, 30, 25, 35, 22, 850],
    "quantity": [1, 1, 2, 3, 1, 2, 1],
    "order_date": pd.to_datetime([
        "2024-01-01", "2024-01-02", "2024-01-03",
        "2024-01-04", "2024-01-05", "2024-01-06", "2024-01-07"
    ])
}

df = pd.DataFrame(data)
df['order_value'] = df['price'] * df['quantity']
tot_val_df = df.groupby('customer', as_index=False).agg(total_order_value=('order_value', 'sum'))

freq_df = df.groupby('product', as_index=False).agg(order_count=('order_id', 'count')).sort_values(by='order_count', ascending=False).head(1)
freq_df['product'].to_list()

avg_val = df.groupby('product', as_index=False).agg(avg_order_val=('order_value', 'mean'))

highest_day = df.groupby('order_date', as_index=False).agg(total_revenue=('order_value', 'sum')).sort_values(by='total_revenue', ascending=False).head(1)

largest_quant = df.groupby('customer', as_index=False).agg(item_quantity=('quantity', 'sum')).sort_values(by='item_quantity', ascending=False).head(1)
largest_quant['customer'].to_list()

['Alice']

In [201]:
"""
	1.	Find the average salary per department.
	2.	List employees who have been at the company more than 3 years.
	3.	Find the highest-paid employee in IT.
	4.	For each department, calculate the total salary cost.
	5.	Which department has the highest average years_at_company?
"""
import pandas as pd

data = {
    "employee_id": [101, 102, 103, 104, 105, 106],
    "name": ["Alice", "Bob", "Charlie", "Diana", "Evan", "Fiona"],
    "department": ["HR", "IT", "IT", "Finance", "Finance", "HR"],
    "salary": [50000, 60000, 55000, 65000, 62000, 48000],
    "years_at_company": [5, 3, 4, 6, 2, 1]
}

df = pd.DataFrame(data)

avg_dept_salary = df.groupby('department', as_index=False).agg(avg_salary=('salary', 'mean'))

min_3 = df[df['years_at_company'] > 3]
min_3 = min_3.copy()
min_3['name'].to_list()

highest_paid_IT = df[df['department'] == 'IT'].nlargest(1, 'salary')
highest_paid_IT['name'].to_list()

dept_salaries = df.groupby('department', as_index=False).agg(total_salary_cost=('salary', 'sum'))
dept_tenure = df.groupby('department', as_index=False).agg(avg_years=('years_at_company', 'mean'))
highest_tenure = dept_tenure.iloc[dept_tenure['avg_years'].idxmax()]
highest_tenure
# ............start by running this and submitting to techsupport. the logic is fine, but the syntax could use help

department    Finance
avg_years         4.0
Name: 0, dtype: object

In [ ]:
"""
    1.	Find the total sales per customer.
	2.	For each category, find the average order amount.
	3.	Which customer spent the most in total?
"""

import pandas as pd

data = {
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer": ["Alice", "Bob", "Alice", "Diana", "Bob", "Alice"],
    "category": ["Books", "Electronics", "Books", "Books", "Electronics", "Clothing"],
    "amount": [25, 200, 40, 15, 150, 60],
    "date": pd.to_datetime([
        "2024-01-01", "2024-01-02", "2024-01-03",
        "2024-01-04", "2024-01-05", "2024-01-06"
    ])
}

df = pd.DataFrame(data)

tot_sales = df.groupby('customer', as_index=False).agg(total_sales=('order_id', 'count'))
tot_sales 
avg_order_amt = df.groupby('category').agg(avg_order_amount=('amount', 'mean')).reset_index()
avg_order_amt
most_spend = df.groupby('customer').agg(total_spend=('amount', 'sum')).reset_index().nlargest(1, 'total_spend')
most_spend

  customer  total_sales
0    Alice            3
1      Bob            2
2    Diana            1

In [ ]:
"""
Task:
	1.	Filter the ratings to only include those from the year 2023.
	2.	Find the average rating per movie.
	3.	Return the top 5 movies with the highest average rating (only include movies with at least 20 ratings).

💡 Bonus: Add a column rating_level that categorizes each rating as: "low" if rating < 2.8 | "medium" if 2.8 ≤ rating < 3 | "high" if rating ≥ 3
"""
import pandas as pd
import numpy as np

# --- Step 1: Generate sample dataset ---
np.random.seed(42)

n = 500  # number of ratings
users = np.arange(1, 51)  # 50 users
movies = ["Inception", "Interstellar", "The Dark Knight", "Memento", "Dunkirk",
          "Oppenheimer", "Tenet", "Prestige", "Insomnia", "Batman Begins"]

ratings = pd.DataFrame({
    "user_id": np.random.choice(users, size=n),
    "movie": np.random.choice(movies, size=n),
    "rating": np.round(np.random.uniform(1, 5, size=n), 1),
    "timestamp": pd.to_datetime(
        np.random.choice(pd.date_range("2022-01-01", "2023-12-31", freq="D"), size=n)
    )
})

filtered = ratings[ratings['timestamp'].dt.year == 2023]
filtered = filtered.copy()

conditions = [(filtered['rating'] < 2.8)
                , (filtered['rating'] < 3)
                , (filtered['rating'] >= 3)
                ]
choices = ['low', 'medium', 'high']
filtered['rating_level'] = np.select(conditions, choices, default='other')

grouped = filtered.groupby('movie').agg(avg_rating=('rating', 'mean'), rating_count= ('rating', 'count')).reset_index()


output = grouped[grouped['rating_count'] >= 20].nlargest(5, 'avg_rating').reset_index(drop=True)
output

             movie  avg_rating  rating_count
0          Dunkirk    3.206061            33
1    Batman Begins    3.136000            25
2      Oppenheimer    3.095000            20
3        Inception    3.050000            30
4  The Dark Knight    3.000000            28

In [142]:
"""
	1.	Extract month as month name.
	2.	Build a summary table of total revenue by month × status.
	3.	Output format should be wide (one row per month, 
        one column per status, values = total revenue).
	4.	Fill missing cells with 0.
	5.	Sort months chronologically, not alphabetically.
"""
import pandas as pd

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107],
    "customer_id": [1, 2, 1, 3, 4, 2, 5],
    "order_date": pd.to_datetime([
        "2024-01-15", "2024-01-22", "2024-02-10",
        "2024-02-28", "2024-03-03", "2024-03-21", "2024-03-15"
    ]),
    "status": [
        "shipped", "delivered", "pending", "shipped",
        "delivered", "cancelled", "shipped"
    ],
    "total_amount": [200, 150, 300, 400, 250, 500, 350]
})

orders['month_name'] = orders['order_date'].dt.month_name()
orders['month_num'] = orders['order_date'].dt.month
p_table = (orders.pivot_table(
    index=['month_name', 'month_num']
    , columns='status'
    , values='total_amount'
    , aggfunc={'total_amount': 'sum'})
    .fillna(0)
    .sort_values(by=['month_num'])
    .reset_index(inplace=False)
    .drop('month_num', axis='columns')
)
p_table.columns.name = None
p_table
# p_table.set_index('month_name')
# .drop(['month_num'], axis='columns')
# orders

  month_name  cancelled  delivered  pending  shipped
0    January        0.0      150.0      0.0    200.0
1   February        0.0        0.0    300.0    400.0
2      March      500.0      250.0      0.0    350.0

In [96]:
"""
	1.	Consider only 2024 orders.
	2.	Find customers who have no orders in 2024.
	3.	Output: customer_id, name.
	4.	Sort by customer_id.
"""
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "name": ["Alice", "Bob", "Charlie", "Diana", "Eve"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106],
    "customer_id": [1, 2, 1, 3, 4, 2],
    "order_date": pd.to_datetime([
        "2023-12-30", "2024-01-15", "2024-02-10",
        "2024-03-01", "2024-01-20", "2023-11-05"
    ])
})


orders_24 = orders[orders['order_date'].dt.year == 2024]
orders_24 = orders_24.copy()

merged = pd.merge(customers, orders_24, how='left', on='customer_id')

filtered = merged[merged['order_id'].isnull()]

filtered[['customer_id', 'name']].sort_values('customer_id')

   customer_id name
4            5  Eve

In [ ]:
"""
	1.	Strip whitespace and lowercase the email column.
	2.	Extract the domain (the part after @) into a new column domain.
	3.	Count how many users per domain.
	4.	Keep only domains with more than 1 user.
	5.	Sort by count descending, then domain name.

Output columns: domain, user_count.
"""

import pandas as pd

users = pd.DataFrame({
    "user_id": [1, 2, 3, 4, 5],
    "email": [
        "  ALICE@example.com  ",
        "bob.smith@work-mail.org",
        "charlie@Example.COM",
        "diana_77@personal.co.uk",
        "eve@example.com"
    ]
})

users['email'] = (users['email']
                  .str.lower()
                  .str.strip())

users['domain'] = [x.split('@')[-1] for x in users['email']]
df = users.groupby('domain').agg(user_count=('user_id', 'count')).reset_index()
new_df = df[df['user_count'] > 1].sort_values(by=['user_count', 'domain'], ascending=[False, True])
new_df

        domain  user_count
0  example.com           3

In [ ]:
"""
From orders (with order_id, customer_id, order_date, status, total_amount):
	1.	Keep only orders that are:
	•	status in ["shipped", "delivered"]
	•	order_date in 2024
	2.	Add a column month as the month name from order_date.
	3.	For each month, calculate:
	•	total revenue
	•	number of unique customers
	4.	Sort months by total revenue descending.
	5.	Output columns: month, total_revenue, unique_customers.
"""

import pandas as pd

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "customer_id": [1, 2, 1, 3, 4, 2, 1, 3],
    "order_date": pd.to_datetime([
        "2024-01-15", "2024-01-22", "2024-02-10", "2024-02-28",
        "2024-03-03", "2024-03-21", "2023-12-30", "2024-03-15"
    ]),
    "status": [
        "shipped", "delivered", "pending", "shipped",
        "delivered", "cancelled", "shipped", "delivered"
    ],
    "total_amount": [200, 150, 300, 400, 250, 500, 180, 350]
})

stati = ['shipped', 'delivered']

filtered = orders[(orders['status'].isin(stati)) & (orders['order_date'].dt.year == 2024)]
filtered = filtered.copy()
filtered['month'] = filtered['order_date'].dt.month_name()

output = (filtered.groupby('month')
          .agg(total_revenue=('total_amount', 'sum'), unique_customers=('customer_id', 'nunique'))
          .sort_values(by='total_revenue', ascending=False)
          .reset_index()
)
output

      month  total_revenue  unique_customers
0     March            600                 2
1  February            400                 1
2   January            350                 2

In [1]:
# Your turn:
	# 2.	Join them so you can see product_name and price_per_unit in the orders data.
	# 3.	Add a total_price column = quantity * price_per_unit.
	# 4.	Group by customer_id and calculate: Total quantity purchased, Total amount spent.
	# 5.	Sort by total amount spent in descending order.

import pandas as pd

# Orders DataFrame
orders_data = {
    "order_id": [1, 2, 3, 4, 5],
    "customer_id": [101, 102, 101, 103, 101],
    "order_date": ["2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03"],
    "product_id": ["P1", "P2", "P3", "P1", "P2"],
    "quantity": [1, 2, 1, 1, 3]
}
orders = pd.DataFrame(orders_data)

# Products DataFrame
products_data = {
    "product_id": ["P1", "P2", "P3"],
    "product_name": ["Laptop", "Mouse", "Monitor"],
    "price_per_unit": [900, 20, 200]
}
products = pd.DataFrame(products_data)

merged = pd.merge(orders, products, how='inner', on='product_id')
merged['total_price'] = merged['quantity'] * merged['price_per_unit']
df = (merged.groupby('customer_id').
      agg(total_quantity_purchased=('quantity', 'sum'), 
          total_amount_spent=('total_price', 'sum')).
          reset_index().
          sort_values(by='total_amount_spent', ascending=False))
df

   customer_id  total_quantity_purchased  total_amount_spent
0          101                         5                1160
2          103                         1                 900
1          102                         2                  40

In [ ]:
"""
Task: Get the top product per customer by total spending.
	1.	Start from the merged DataFrame (orders + products).
	2.	Calculate total_price (you already know this).
	3.	Group by both customer_id and product_name, summing up total_price.
	4.	For each customer, keep only the product with the highest total spending.
	5.	Sort the final result by customer_id.
"""
merged['total_price'] = merged['quantity'] * merged['price_per_unit']
df = (
    merged.groupby(['customer_id', 'product_name'])['total_price'].
    sum().
    reset_index()
      )
df.groupby('customer_id', group_keys=False).apply(lambda x: x.nlargest(1, 'total_price')).sort_values(by='customer_id').reset_index(drop=True)

/var/folders/wc/8wws1lfd3kv91ykflkc2lzxc0000gn/T/ipykernel_71456/66499867.py:17: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('customer_id').apply(lambda x: x.nlargest(1, 'total_price')).reset_index().sort_values(by='customer_id')

ValueError: cannot insert customer_id, already exists

In [ ]:
import pandas as pd

# Step 1: Create the DataFrame
data = {
    "date": ["2024-02-01", "2024-02-01", "2024-02-01",
             "2024-02-02", "2024-02-02", "2024-02-02"],
    "user_id": [1, 2, 3, 1, 2, 3],
    "page_views": [5, 3, 8, 4, 6, 7],
    "clicks": [2, 1, 4, 2, 3, 2]
}

df = pd.DataFrame(data)

# Your turn:
df['date'] = pd.to_datetime(df['date'])
# Step 2: Group by date and calculate totals + CTR: total_page_views, total_clicks
new_df = df.groupby('date').agg(total_page_views=('page_views', 'sum'), total_clicks=('clicks', 'sum')).reset_index()
# Step 3: Sort by CTR (descending): (CTR) = total_clicks / total_page_views.
new_df['ctr'] = new_df['total_clicks'] / new_df['total_page_views']
new_df

        date  total_page_views  total_clicks       ctr
0 2024-02-01                16             7  0.437500
1 2024-02-02                17             7  0.411765

In [89]:
"""
Task:
	1.	Hardcode the data into a DataFrame.
	2.	Calculate CTR per user per day = clicks / page_views.
	3.	Group by date and calculate the average CTR across all users.
	4.	Sort by average CTR in descending order.
"""
new_df = df.groupby(['user_id', 'date']).agg({'clicks': 'sum', 'page_views': 'sum'}).reset_index()
new_df['ctr'] =  new_df['clicks'] / new_df['page_views']
output = new_df.groupby('date').agg(avg_ctr=('ctr', 'mean')).sort_values(by='avg_ctr', ascending=False).reset_index()
output

        date   avg_ctr
0 2024-02-02  0.428571
1 2024-02-01  0.411111

In [79]:
import pandas as pd

# Step 1: Create the DataFrame
data = {
    "order_id": [1, 2, 3, 4, 5],
    "customer_id": [101, 102, 101, 103, 101],
    "order_date": ["2024-01-02", "2024-01-03", "2024-01-05", "2024-01-06", "2024-01-07"],
    "product": ["Laptop", "Mouse", "Monitor", "Laptop", "Mouse"],
    "quantity": [1, 2, 1, 1, 3],
    "price_per_unit": [900, 20, 200, 950, 18]
}

df = pd.DataFrame(data)

# Step 2: Add total_price column
df['total_price'] = df['quantity'] * df['price_per_unit']
# Step 3: Group by customer_id and calculate totals
new_df = df.groupby('customer_id').agg(total_quantity=('quantity', 'sum'), total_spent=('total_price', 'sum')).sort_values(by='total_spent', ascending=False).reset_index()
# Step 4: Sort by total amount spent (descending)

new_df

   customer_id  total_quantity  total_spent
0          101               5         1154
1          103               1          950
2          102               2           40

In [ ]:
"""
Task:
	1.	For each customer, and for each order date, calculate in the previous 90 days (including that date):
	•	rolling_orders: total number of orders
	•	rolling_spent: total amount spent
	2.	Mark a customer as “rolling loyal” on that date if:
	•	rolling_orders ≥ 3
	•	rolling_spent > the overall average order amount per customer in the dataset
	3.	Return a DataFrame with:
	•	customer_id, order_date, rolling_orders, rolling_spent, is_rolling_loyal
"""
import pandas as pd

sales = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105, 106, 107, 108, 109],
    'customer_id': [1, 1, 2, 3, 2, 4, 3, 1, 2],
    'order_date': pd.to_datetime([
        '2023-01-05', '2023-01-20', '2023-02-02', '2023-02-15', '2023-02-20',
        '2023-03-05', '2023-03-18', '2023-04-02', '2023-04-10'
    ]),
    'amount': [200, 150, 300, 100, 250, 400, 350, 180, 500]
})

sales = sales.sort_values(by=['customer_id', 'order_date'])
df = (sales.groupby(['customer_id']).rolling(window='90D', on='order_date', closed='both').
      agg(
          {'order_id':'count', 'amount':'sum'}).
          rename(columns={'order_id':'rolling_orders', 'amount':'rolling_spent'}).
          reset_index())

df

   order_id  customer_id order_date  amount
0       101            1 2023-01-05     200
1       102            1 2023-01-20     150
7       108            1 2023-04-02     180
2       103            2 2023-02-02     300
4       105            2 2023-02-20     250
8       109            2 2023-04-10     500
3       104            3 2023-02-15     100
6       107            3 2023-03-18     350
5       106            4 2023-03-05     400

In [21]:
"""
1.	For each customer, calculate:
	•	first_order_date
	•	last_order_date
	•	total_orders (number of orders)
	•	total_spent (sum of amount)
2.	Find loyal customers, defined as customers with at least 2 orders and total_spent above the average total spent across all customers.
3.	Return a final DataFrame with:
	•	customer_id, first_order_date, last_order_date, total_orders, total_spent
	•	is_loyal column (True / False)
"""

import pandas as pd

sales = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105, 106, 107],
    'customer_id': [1, 1, 2, 3, 2, 4, 3],
    'order_date': pd.to_datetime([
        '2023-01-05', '2023-01-20', '2023-02-02',
        '2023-02-15', '2023-02-20', '2023-03-05', '2023-03-18'
    ]),
    'amount': [200, 150, 300, 100, 250, 400, 350]
})

df = (sales.groupby('customer_id').
      agg(first_order_date=('order_date', 'min'), last_order_date=('order_date', 'max'), total_orders=('order_id', 'count'), total_spent=('amount', 'sum')).
      reset_index()
      )

df['is_loyal'] = (df['total_orders'] >= 2) & (df['total_spent'] > df['total_spent'].mean())
df

,customer_id,first_order_date,last_order_date,total_orders,total_spent,is_loyal
0,1,2023-01-05,2023-01-20,2,350,False
1,2,2023-02-02,2023-02-20,2,550,True
2,3,2023-02-15,2023-03-18,2,450,True
3,4,2023-03-05,2023-03-05,1,400,False

In [7]:
"""
	1.	For each month, compute:
	•	monthly_orders: total number of orders
	•	unique_customers: number of distinct customers
	•	total_revenue: total amount spent
	2.	Identify “peak months” where:
	•	Revenue is above the average monthly revenue
	3.	Return a final DataFrame with:
	•	month (as YYYY-MM)
	•	monthly_orders, unique_customers, total_revenue
	•	is_peak: True if it’s a peak month, else False
"""
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'order_id': [601, 602, 603, 604, 605, 606, 607, 608, 609, 610],
    'customer_id': [1, 2, 1, 3, 2, 3, 1, 2, 3, 1],
    'order_date': pd.to_datetime([
        '2023-01-10', '2023-01-20', '2023-02-15', '2023-02-20', '2023-03-05',
        '2023-03-10', '2023-04-01', '2023-04-05', '2023-04-15', '2023-05-01'
    ]),
    'amount': [80, 100, 90, 120, 110, 130, 150, 140, 160, 170]
})

monthlies = (orders.groupby(orders['order_date'].dt.to_period('M').astype(str)).
             agg(monthly_orders=('order_id', 'count'), unique_customers=('customer_id', 'nunique'), total_revenue=('amount', 'sum')).         
             reset_index().
             rename(columns={'order_date': 'month'})
             )

monthlies['is_peak'] = monthlies['total_revenue'] > monthlies['total_revenue'].mean()
monthlies

     month  monthly_orders  unique_customers  total_revenue  is_peak
0  2023-01               2                 2            180    False
1  2023-02               2                 2            210    False
2  2023-03               2                 2            240    False
3  2023-04               3                 3            450     True
4  2023-05               1                 1            170    False

In [ ]:
"""
🧠 Task:
	1.	For each customer, compute:
	•	total_orders: total number of orders
	•	total_spent: total amount spent
	•	first_order: date of their first order
	•	last_order: date of their last order
	2.	Create a column customer_status using multi-condition logic:
	•	'new' if first_order is in April 2023 or later
	•	'churned' if last_order is before March 1, 2023
	•	'active' otherwise

"""
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'order_id': [601, 602, 603, 604, 605, 606, 607, 608, 609, 610],
    'customer_id': [1, 2, 1, 3, 2, 3, 1, 2, 3, 1],
    'order_date': pd.to_datetime([
        '2023-01-10', '2023-01-20', '2023-02-15', '2023-02-20', '2023-03-05',
        '2023-03-10', '2023-04-01', '2023-04-05', '2023-04-15', '2023-05-01'
    ]),
    'amount': [80, 100, 90, 120, 110, 130, 150, 140, 160, 170]
})

# grouped = orders.groupby('customer_id').agg(
#     total_orders=('order_id', 'count'),
#     total_spent=('amount', 'sum'),
#     first_order=('order_date', 'min'),
#     last_order=('order_date', 'max')
# ).reset_index()

# conditions = [
#     grouped['first_order'] >= pd.to_datetime('2023-04-01'),
#     grouped['last_order'] < pd.to_datetime('2023-03-01')
# ]
# choices = ['new', 'churned']

# grouped['customer_status'] = np.select(conditions, choices, default='active')
# grouped

,customer_id,total_orders,total_spent,first_order,last_order,customer_status
0,1,4,490,2023-01-10,2023-05-01,active
1,2,3,350,2023-01-20,2023-04-05,active
2,3,3,410,2023-02-20,2023-04-15,active

In [1]:
"""
🧠 Task:
	1.	Filter: Keep only customers who signed up before March 1, 2023.
	2.	Join: Merge with orders to get their order history.
	3.	Compute per customer:
	•	order_count: total number of orders
	•	total_spent: total amount spent
	4.	Add: A column loyalty_tag:
	•	"high" if total_spent ≥ 400
	•	"medium" if 200 ≤ total_spent < 400
	•	"low" otherwise
"""

import pandas as pd

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'signup_date': pd.to_datetime(['2022-12-01', '2023-01-15', '2023-02-10', '2023-04-01'])
})

orders = pd.DataFrame({
    'order_id': [501, 502, 503, 504, 505, 506, 507, 508],
    'customer_id': [1, 2, 1, 3, 2, 3, 1, 4],
    'order_date': pd.to_datetime([
        '2023-03-01', '2023-03-05', '2023-03-20', '2023-03-25',
        '2023-04-05', '2023-04-10', '2023-04-15', '2023-04-20'
    ]),
    'amount': [100, 200, 150, 120, 180, 130, 160, 90]
})

filtered = customers[customers['signup_date'] < pd.Timestamp('2023-03-01')]
filtered = filtered.copy()
merged = pd.merge(filtered, orders, how='inner', on='customer_id')
grouped = merged.groupby('customer_id').agg(order_count=('order_id', 'count'), total_spent=('amount', 'sum')).reset_index()
grouped['loyalty_tag'] = ['high' if x >= 400 else 'medium' if x >= 200 else 'low' for x in grouped['total_spent']]
grouped

   customer_id  order_count  total_spent loyalty_tag
0            1            3          410        high
1            2            2          380      medium
2            3            2          250      medium

In [309]:
"""
	1.	Filter orders from March 2023 onward
	2.	For each customer, calculate:
	•	recent_order_count: number of orders since March 1, 2023
	•	recent_total_spent: total amount spent since that date
	3.	Add a boolean column is_recent_big_spender:
	•	True if recent_total_spent > $250
	•	False otherwise
"""


import pandas as pd

orders = pd.DataFrame({
    'order_id': [401, 402, 403, 404, 405, 406, 407, 408, 409, 410],
    'customer_id': [1, 2, 1, 3, 2, 3, 1, 2, 3, 1],
    'order_date': pd.to_datetime([
        '2023-02-15', '2023-02-20', '2023-03-05', '2023-03-10', '2023-03-15',
        '2023-03-20', '2023-04-01', '2023-04-10', '2023-04-15', '2023-04-20'
    ]),
    'amount': [80, 120, 150, 90, 160, 110, 200, 100, 130, 180]
})

filtered = orders[orders['order_date'] >= '2023-03-01']
filtered = filtered.copy()
df = filtered.groupby('customer_id').agg(recent_order_count=('order_id', 'count'), recent_total_spent=('amount', 'sum')).reset_index()
# df['is_recent_big_spender'] = df['recent_total_spent'].apply(lambda x: x > 250)
df['is_recent_big_spender'] = df['recent_total_spent'] > 250

df

   customer_id  recent_order_count  recent_total_spent  is_recent_big_spender
0            1                   3                 530                   True
1            2                   2                 260                   True
2            3                   3                 330                   True

In [294]:
"""
🧠 Problem: High-Value Repeat Customers
🎯 Tasks:
	1.	Create a customer-level summary with:
	•	total number of orders
	•	total amount spent
	2.	Add a boolean flag called is_high_value_repeat:
	•	True if a customer has more than 2 orders and total amount spent is over $300
	•	False otherwise
"""
import pandas as pd

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105, 106, 107, 108],
    'customer_id': [1, 1, 2, 2, 3, 1, 2, 3],
    'order_date': pd.to_datetime([
        '2023-01-10', '2023-01-17', '2023-01-12',
        '2023-01-20', '2023-01-25', '2023-02-01',
        '2023-02-05', '2023-02-10'
    ]),
    'amount': [120, 80, 150, 200, 50, 70, 180, 30]
})

summary = orders.groupby('customer_id').agg({'order_id': 'count', 'amount': 'sum'}).reset_index().rename(columns={'order_id': 'order_count', 'amount': 'total_spent'})
summary['is_high_value_repeat'] = ((summary['order_count'] > 2)  & (summary['total_spent'] > 300))
summary

   customer_id  order_count  total_spent  is_high_value_repeat
0            1            3          270                 False
1            2            3          530                  True
2            3            2           80                 False

In [ ]:
"""
Tasks:
	1.	Total amount spent per customer
	2.	Number of orders per customer
	3.	Customer with the highest average order value
	4.	For each customer, days between their first and last order
"""
import pandas as pd

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105, 106],
    'customer_id': [1, 1, 2, 2, 3, 1],
    'order_date': pd.to_datetime([
        '2023-01-10', '2023-01-17', '2023-01-12',
        '2023-01-20', '2023-01-25', '2023-02-01'
    ]),
    'amount': [120, 80, 150, 200, 50, 70]
})

specs = orders.groupby('customer_id').agg({'amount': 'sum', 'order_id': 'count'}).reset_index().rename(columns={'amount': 'total_amount', 'order_id': 'order_count'})

highest_avg = orders.groupby('customer_id')['amount'].mean().reset_index().nlargest(1, 'amount')
# specs['highest'] = orders['customer_id'] == highest_avg['customer_id'].max()

days_between = orders.groupby('customer_id')['order_date'].agg(['min','max']).reset_index().rename(columns={'min': 'first_order_date', 'max': 'last_order_date'})
days_between['days_between'] = (days_between['last_order_date'] - days_between['first_order_date']).dt.days

merged = pd.merge(specs, days_between, how='inner', on='customer_id')
merged

,customer_id,total_amount,order_count,highest,first_order_date,last_order_date,days_between
0,1,270,3,False,2023-01-10,2023-02-01,22
1,2,350,2,False,2023-01-12,2023-01-20,8
2,3,50,1,True,2023-01-25,2023-01-25,0

In [ ]:
"""
Task:
Filter df to keep only rows where the 'text' contains a 4-digit number starting with '20' (like a year).
Pattern: '20\d{2}'
Give it a try using .str.contains() with regex=True.
"""

In [210]:
import pandas as pd
import re 

df = pd.DataFrame({
    'text': ['Order 123 shipped on 2023-07-15', 'Invoice #4567 dated 2022/12/01', 'Ref: 89, due 01-01-2025']
})

# Create a new column 'numbers' that contains a list of all number groups (i.e., sequences of digits) found in each row.

df['numbers'] = df['text'].apply(lambda x: re.findall('[0-9]+', x))

df['output'] = df['numbers'].apply(lambda x: x if len(x) > 3 else 0)
df 


# for t in text 
# extract numbers with findall() (set to int?)
# if len(num) = 4 and startswith? 20
# include 

# df[len(df['text']) > 20]

                              text               numbers                output
0  Order 123 shipped on 2023-07-15   [123, 2023, 07, 15]   [123, 2023, 07, 15]
1   Invoice #4567 dated 2022/12/01  [4567, 2022, 12, 01]  [4567, 2022, 12, 01]
2          Ref: 89, due 01-01-2025    [89, 01, 01, 2025]    [89, 01, 01, 2025]

In [193]:
import pandas as pd 
import re 

df = pd.DataFrame({
    'code': [' abc-123 ', 'X#YZ_789', '  42*gold!', ' cleanCode99 ']
})

# df['clean_code'] = df['code'].apply(lambda x: re.sub('[^a-zA-Z0-9]', '', x.strip().lower()))

# From the same df['code'], extract only the numeric part into a new column 'digits'.

df['digits'] = df['code'].apply(lambda x: re.sub('[^0-9]', '', x))
df

            code digits
0       abc-123     123
1       X#YZ_789    789
2       42*gold!     42
3   cleanCode99      99

In [188]:
"""
Question:
Clean the 'raw' column by:
	1.	Stripping leading/trailing whitespace
	2.	Removing all non-alphabetic characters
	3.	Converting to lowercase
"""
import pandas as pd
import re 

df = pd.DataFrame({
    'raw': ['  hello ', 'WORLD!!', '  PyThOn3  ', '@data_ ', ' clean ']
})

# df['cleaned'] = df['raw'].str.replace('[^A-Za-z0-9]', '', regex=True).str.lower()

df['cleaned'] = df['raw'].apply(lambda x: re.sub('[^A-Za-z0-9]', '', x.strip().lower()))




df

           raw  cleaned
0       hello     hello
1      WORLD!!    world
2    PyThOn3    python3
3      @data_      data
4       clean     clean

In [72]:
"""
Task: Pivot this data so each student’s name is a row, each subject is a column, and the cell values are the scores.

Expected format:
subject   English  Math
name                    
Alice          92    85
Bob            67    78
Charlie        88    90
"""
import pandas as pd 

data = {
    'name': ['Alice', 'Bob', 'Alice', 'Bob', 'Charlie', 'Charlie'],
    'subject': ['Math', 'Math', 'English', 'English', 'Math', 'English'],
    'score': [85, 78, 92, 67, 90, 88]
}
df = pd.DataFrame(data)

# pivoted = df.pivot(index='name', columns='subject', values='score').reset_index()
# pivoted
# pivoted.groupby('name', as_index=True)['score'].mean()
df.groupby('name')['score'].mean().reset_index()

      name  score
0    Alice   88.5
1      Bob   72.5
2  Charlie   89.0

In [56]:
"""
Question:
Use pandas to filter this DataFrame to only include rows where the score is ≥ 70.
"""
import pandas as pd

names = ['Alice', 'Bob', 'Charlie', 'Dana']
scores = [85, 62, 90, 58]
df = pd.DataFrame({'name': names, 'score': scores})

# df[df['score'] >= 70]

"""
Task: Add a new column to the DataFrame called 'result' that contains 'Pass' if the score is ≥ 70, else 'Fail'.
"""

# df['result'] = ['Pass' if s >= 70 else 'Fail' for s in df['score']]

"""
Recreate the 'result' column using .apply() with a lambda function instead of list comprehension.
"""

df['result'] = df['score'].apply(lambda x: 'Pass' if x >= 70 else 'Fail')
df

      name  score result
0    Alice     85   Pass
1      Bob     62   Fail
2  Charlie     90   Pass
3     Dana     58   Fail

In [ ]:
"""
🧠 Problem: Purchase History by Customer
🛠️ Task:
Use list comprehension to create a list of dictionaries like:

[
  {'customer': 'Alice', 'products': ['Widget', 'Gizmo']},
  {'customer': 'Bob', 'products': ['Gadget', 'Widget']},
  {'customer': 'Dan', 'products': ['Gizmo']},
  {'customer': 'Eve', 'products': ['Gadget', 'Widget']}
]
"""
import pandas as pd

df = pd.DataFrame({
    'customer': ['Alice', 'Bob', 'Alice', 'Dan', 'Bob', 'Eve', 'Eve'],
    'product': ['Widget', 'Gadget', 'Gizmo', 'Gizmo', 'Widget', 'Gadget', 'Widget']
})

dict = {}
list_dict = []

for index, rows in df.iterrows():
    list_dict.get('index') = 
    list_dict.append(rows.tolist())

# list_dict 

df.values.tolist()


output:
{'data': 3, 'is': 3, 'powerful': 1, 'python': 1, 'great': 1, 'for': 1, 'analysis': 2, 'fun': 1}
"""
sentences = [
    "data is powerful",
    "python is great for data analysis",
    "data analysis is fun"
]

output = {}
for s in sentences:
    spl = s.split()
    for w in spl:
        output[w] = output.get(w, 0) + 1
        
# output

[['Alice', 'Widget'],
 ['Bob', 'Gadget'],
 ['Alice', 'Gizmo'],
 ['Dan', 'Gizmo'],
 ['Bob', 'Widget'],
 ['Eve', 'Gadget'],
 ['Eve', 'Widget']]

In [52]:
"""
💼 Problem: Customer Risk Tagging
🛠️ Task:
	1.	Compute total amount and total chargebacks per customer.
	2.	Add a column 'risk' to df using list comprehension, with the following rule:
	•	'high' if total chargebacks ≥ 2 and total amount > 100
	•	'low' otherwise
"""
import pandas as pd

df = pd.DataFrame({
    'customer': ['Alice', 'Bob', 'Alice', 'Dan', 'Bob', 'Eve', 'Eve'],
    'amount': [120, 50, 80, 40, 70, 200, 150],
    'chargebacks': [0, 1, 0, 0, 2, 1, 3]
})

df['tot_amount'] = df.groupby('customer')['amount'].transform('sum')
df['tot_chargebacks'] = df.groupby('customer')['chargebacks'].transform('sum')
df['risk'] = ['high' if c >= 2 and a > 100 else 'low' for a,c in zip(df['tot_amount'], df['tot_chargebacks'])]
df

  customer  amount  chargebacks  tot_amount  tot_chargebacks  risk
0    Alice     120            0         200                0   low
1      Bob      50            1         120                3  high
2    Alice      80            0         200                0   low
3      Dan      40            0          40                0   low
4      Bob      70            2         120                3  high
5      Eve     200            1         350                4  high
6      Eve     150            3         350                4  high

In [49]:
"""
📦 Problem: Tagging High-Spending Customers
🛠️ Task:
	1.	Compute total amount spent per customer.
	2.	Using list comprehension, create a new column 'tag' in the original df:
	•	'high' if the customer’s total spend is ≥ 200
	•	'low' otherwise
"""
import pandas as pd

df = pd.DataFrame({
    'customer': ['Alice', 'Bob', 'Alice', 'Dan', 'Bob', 'Eve', 'Eve'],
    'amount': [120, 50, 80, 40, 70, 200, 150]
})

# df['spend'] = df.groupby('customer')['amount'].transform('sum')

df['tag'] = ['high' if x >= 200 else 'low' for x in df.groupby('customer')['amount'].transform('sum')]
df
# data = list(zip(df['customer'], df['amount']))
# data

  customer  amount   tag
0    Alice     120  high
1      Bob      50   low
2    Alice      80  high
3      Dan      40   low
4      Bob      70   low
5      Eve     200  high
6      Eve     150  high

In [41]:
"""
🧪 Problem: Scholarship Eligibility
🛠️ Task:
Using list comprehension, create a new column 'eligible' with these rules:
	•	If (score + extra_credit) >= 90 and discipline_flag == 0, then 'yes'
	•	Otherwise, 'no'
"""
import pandas as pd

df = pd.DataFrame({
    'student': ['Amy', 'Ben', 'Cara', 'Dan', 'Eve'],
    'score': [88, 92, 70, 65, 85],
    'extra_credit': [5, 0, 10, 15, 0],
    'discipline_flag': [0, 1, 0, 0, 1]  # 0 = good, 1 = flagged
})

df['eligible'] = ['yes' if s + e >= 90 and d == 0
                  else 'no'
                  for s, e, d in zip(df['score'], df['extra_credit'], df['discipline_flag'])]
df

  student  score  extra_credit  discipline_flag eligible
0     Amy     88             5                0      yes
1     Ben     92             0                1       no
2    Cara     70            10                0       no
3     Dan     65            15                0       no
4     Eve     85             0                1       no

In [40]:
"""
🧠 Problem: Pass/Fail with Bonus Rule
🛠️ Task:
Using list comprehension, add a new column 'result' based on the following rule:
	•	If score + extra_credit ≥ 60, label as "pass"
	•	Otherwise, label as "fail"
"""
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'student': ['Alex', 'Bri', 'Chris', 'Dana', 'Eli'],
    'score': [55, 62, 49, 85, 58],
    'extra_credit': [10, 0, 5, 0, 7]
})

# df['result'] = np.where(df['score'] + df['extra_credit'] >= 60, 'pass', 'fail')
df['result'] = ['pass' if s + e >= 60
                else 'fail'
                for s,e in zip(df['score'], df['extra_credit'])
                ]
df

  student  score  extra_credit result
0    Alex     55            10   pass
1     Bri     62             0   pass
2   Chris     49             5   fail
3    Dana     85             0   pass
4     Eli     58             7   pass

In [36]:
"""
📦 Problem: Tagging Products Based on Sales
🛠️ Task:
Using list comprehension, add a new column 'tag' with these rules:
	•	"bestseller" if units_sold ≥ 100
	•	"average" if 50 ≤ units_sold < 100
	•	"low" if less than 50
"""
import pandas as pd

df = pd.DataFrame({
    'product': ['Widget', 'Gadget', 'Gizmo', 'Thingy', 'Doodad'],
    'units_sold': [120, 35, 200, 15, 80]
})

df['tag'] = ['bestseller' if x >= 100 
             else 'average' if x < 100 and x >= 50 
             else 'low' 
             for x in df['units_sold']]
df

  product  units_sold         tag
0  Widget         120  bestseller
1  Gadget          35         low
2   Gizmo         200  bestseller
3  Thingy          15         low
4  Doodad          80     average

In [ ]:
"""
📊 Problem: Customer Product Summary
🛠️ Task:
	1.	Create a list of unique customers.
	2.	Use list comprehension to build a list of tuples, where each tuple is:

(customer_name, total_units_ordered)

	3.	Convert that list into a new DataFrame with columns: 'customer', 'total_quantity'.
"""
import pandas as pd

df = pd.DataFrame({
    'customer': ['Alice', 'Bob', 'Alice', 'David', 'Bob', 'Alice'],
    'product': ['Widget', 'Gadget', 'Gizmo', 'Gizmo', 'Widget', 'Gadget'],
    'quantity': [3, 2, 1, 4, 2, 5]
})

new_df = df.groupby('customer')['quantity'].sum().reset_index()

tuple_list = [tuple(row) for index, row in new_df.iterrows()]
column_names = ['customer', 'total_quantity']

output = pd.DataFrame(tuple_list, columns=column_names)
output

  customer  total_quantity
0    Alice               9
1      Bob               4
2    David               4

In [ ]:
"""
🧪 Problem: Analyze Sales Data
Task:
	1.	Add a column total which is quantity * price.
	2.	Convert date to a datetime object.
	3.	Find the total sales per customer.
	4.	Find the top 3 products by total sales.
	5.	Filter to include only orders in 2023.
"""
import pandas as pd

data = {
    'order_id': [1001, 1002, 1003, 1004, 1005, 1006],
    'customer': ['Alice', 'Bob', 'Alice', 'David', 'Bob', 'Alice'],
    'product': ['Widget', 'Gadget', 'Widget', 'Gizmo', 'Gadget', 'Gizmo'],
    'quantity': [3, 2, 5, 1, 4, 2],
    'price': [20.0, 15.0, 20.0, 50.0, 15.0, 50.0],
    'date': ['2023-01-15', '2023-02-10', '2022-12-20', '2023-03-05', '2023-04-12', '2022-11-01']
}

df = pd.DataFrame(data)

# 1. 
df['total'] = df['quantity'] * df['price']

# 2. 
df['date'] = pd.to_datetime(df['date'])

# 3. 
sales_per_cust = df.groupby('customer')['total'].sum()

# 4. 
top_3 = df.groupby('product')['total'].sum().nlargest(3)

# 5. 
orders_2023 = df[df['date'].dt.year == 2023]

   order_id customer product  quantity  price       date  total
0      1001    Alice  Widget         3   20.0 2023-01-15   60.0
1      1002      Bob  Gadget         2   15.0 2023-02-10   30.0
3      1004    David   Gizmo         1   50.0 2023-03-05   50.0
4      1005      Bob  Gadget         4   15.0 2023-04-12   60.0

In [ ]:
"""
🎯 Task: Add a new column 'domain' using a list comprehension that extracts just the domain name (e.g., 'gmail.com', 'yahoo.com', etc.).
"""
import pandas as pd

df = pd.DataFrame({
    'email': ['alice@gmail.com', 'bob@yahoo.com', 'cathy@outlook.com', 'david@gmail.com']
})
# extract...split string, get index == 1

df['domain'] = [x.split('@')[-1] for x in df['email']]

               email       domain
0    alice@gmail.com    gmail.com
1      bob@yahoo.com    yahoo.com
2  cathy@outlook.com  outlook.com
3    david@gmail.com    gmail.com

In [50]:
"""
🔤 List Comprehension Practice: Name Flags
Create a new column 'proper_case' using a list comprehension:
	•	True if the name is in title case (first letter capitalized in each word)
	•	False otherwise

"""
import pandas as pd

df = pd.DataFrame({
    'name': ['Alice Smith', 'bob jones', 'Cathy Lee', 'david brown', 'Eva Green']
})

df['proper_case'] = [x.istitle() for x in df['name']]
df

          name  proper_case
0  Alice Smith         True
1    bob jones        False
2    Cathy Lee         True
3  david brown        False
4    Eva Green         True

In [ ]:
"""
🧠 List Comprehension Practice: Product Tags
Add a new column 'tag' using a list comprehension with this logic:
	•	"Expensive" if price > 500
	•	"Mid" if price is between 100 and 500 (inclusive)
	•	"Cheap" if price < 100
"""
import pandas as pd

df = pd.DataFrame({
    'product': ['Desk', 'Chair', 'iPad', 'Monitor', 'Notebook', 'Mouse'],
    'price': [200, 100, 799, 250, 5, 40]
})

df['tag'] = ['Expensive' if x > 500 else 'Mid' if x >= 100 and x < 500 else 'Cheap' for x in df['price']]
df

    product  price        tag
0      Desk    200        Mid
1     Chair    100        Mid
2      iPad    799  Expensive
3   Monitor    250        Mid
4  Notebook      5      Cheap
5     Mouse     40      Cheap

In [41]:
"""
📊 Practice Problem: Top Store per Region
🎯 Tasks:
	1.	Find the store with the highest sales in each region.
	2.	Return a new DataFrame with just those top-performing stores.
"""
import pandas as pd

df = pd.DataFrame({
    'store': ['A', 'B', 'C', 'D', 'E', 'F'],
    'region': ['North', 'North', 'South', 'South', 'East', 'East'],
    'sales': [5000, 7000, 6000, 3000, 4000, 9000]
})


# df_largest = df.nlargest(1, 'sales')
# df['max_sales'] = 
# df.groupby('region')['sales'].nlargest(1)

df.groupby('region', group_keys=False).apply(lambda g: g.nlargest(1, 'sales'))

/var/folders/wc/8wws1lfd3kv91ykflkc2lzxc0000gn/T/ipykernel_12828/1797184555.py:20: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('region', group_keys=False).apply(lambda g: g.nlargest(1, 'sales'))

  store region  sales
5     F   East   9000
1     B  North   7000
2     C  South   6000

In [23]:
"""
📊 Practice Problem: Product vs. Category Performance

🎯 Tasks:
	1.	Compute the average sales per category
	2.	Join that info back to the original DataFrame
	3.	Add a new column 'above_avg' that is True if the product’s sales are above the category average
"""
import pandas as pd 

df = pd.DataFrame({
    'product_id': ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
    'category': ['Books', 'Books', 'Tech', 'Tech', 'Tech', 'Tech'],
    'sales': [120, 150, 1000, 900, 300, 500]
})

df['avg_sales']= df.groupby('category')['sales'].transform('mean')
df['above_avg'] = df['sales'] > df['avg_sales']
df 


# # merge and create new df
# merged = pd.merge(df, new_df, how='inner', on='category')
# merged
# # create new column

  product_id category  sales  avg_sales  above_avg
0         p1    Books    120      135.0      False
1         p2    Books    150      135.0       True
2         p3     Tech   1000      675.0       True
3         p4     Tech    900      675.0       True
4         p5     Tech    300      675.0      False
5         p6     Tech    500      675.0      False

In [8]:
"""
📊 Practice Problem: Seller Discount Strategy

🎯 Tasks:
	1.	For each seller_id, calculate the average discount_rate and total sales.
	2.	Add a column high_discount_seller that is True if their average discount is >= 0.10

Result:

seller_id | avg_discount | total_sales | high_discount_seller

"""
import pandas as pd

df = pd.DataFrame({
    'seller_id': ['s1', 's1', 's2', 's2', 's3', 's3', 's3'],
    'product_id': ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7'],
    'discount_rate': [0.10, 0.0, 0.15, 0.05, 0.0, 0.2, 0.25],
    'sales': [100, 150, 80, 120, 200, 90, 60]
})

new_df = df.groupby('seller_id').agg({'discount_rate': 'mean', 'sales': 'sum'}).rename(columns={'discount_rate': 'avg_discount', 'sales': 'total_sales'}).reset_index()
new_df['high_discount_seller'] = new_df['avg_discount'].apply(lambda x: x >= 0.10)
new_df


# new_df['at_risk'] = new_df['avg_discount'].apply(lambda x: x < 70)

  seller_id  avg_discount  total_sales  high_discount_seller
0        s1          0.05          250                 False
1        s2          0.10          200                  True
2        s3          0.15          350                  True

In [15]:
"""
📊 Practice Problem: Percentile Rank Within Category
🎯 Task:
	1.	For each category, compute the percentile rank of each product based on sales, scaled from 0 to 1, where:
	•	Highest sales = 1.0
	•	Lowest sales = 0.0
	2.	Add a new column: 'percentile_rank'
"""
import pandas as pd 

df = pd.DataFrame({
    'product_id': [1, 2, 3, 4, 5, 6, 7],
    'category': ['Books', 'Books', 'Books', 'Tech', 'Tech', 'Tech', 'Tech'],
    'sales': [120, 340, 200, 1500, 800, 600, 400]
})

df['cat_ntile'] = df.groupby('category')['sales'].rank(pct=True, ascending=True)
df

   product_id category  sales  cat_ntile
0           1    Books    120   0.333333
1           2    Books    340   1.000000
2           3    Books    200   0.666667
3           4     Tech   1500   1.000000
4           5     Tech    800   0.750000
5           6     Tech    600   0.500000
6           7     Tech    400   0.250000

In [12]:
"""
📊 Practice Problem: Rank Products by Popularity Within Category
🎯 Tasks:
	1.	For each category, rank the products by sales (highest = rank 1).
	2.	Add a new column called 'popularity_rank'.
	3.	Return a DataFrame with:

product_id | category | sales | popularity_rank
"""
import pandas as pd 

df = pd.DataFrame({
    'product_id': [1, 2, 3, 4, 5, 6, 7],
    'category': ['Books', 'Books', 'Books', 'Tech', 'Tech', 'Tech', 'Tech'],
    'sales': [120, 340, 200, 1500, 800, 600, 400]
})

df['popularity_rank'] = df.groupby('category')['sales'].rank(method='dense', ascending=False)
df

   product_id category  sales  popularity_rank
0           1    Books    120              3.0
1           2    Books    340              1.0
2           3    Books    200              2.0
3           4     Tech   1500              1.0
4           5     Tech    800              2.0
5           6     Tech    600              3.0
6           7     Tech    400              4.0

In [8]:
"""
📊 Practice Problem: Product Rating Cleaner
🎯 Tasks:
	1.	Drop products with no reviews (i.e., reviews == 0)
	2.	Fill missing rating values with the average rating per product
	3.	Return a DataFrame with:
	•	product
	•	rating_filled
	•	reviews
"""
import pandas as pd

df = pd.DataFrame({
    'product': ['A', 'A', 'A', 'B', 'B', 'C', 'C', 'D', 'E'],
    'rating': [4.5, 4.7, None, 3.0, None, 4.0, 4.1, None, None],
    'reviews': [10, 8, 5, 2, 1, 20, 15, 0, 0]
})

new_df = df[df['reviews'] > 0].copy()
new_df['rating'] = new_df['rating'].fillna(new_df.groupby('product')['rating'].transform('mean'))
new_df

  product  rating  reviews
0       A     4.5       10
1       A     4.7        8
2       A     4.6        5
3       B     3.0        2
4       B     3.0        1
5       C     4.0       20
6       C     4.1       15

In [177]:
"""
📊 Practice Problem: Incomplete Survey Cleanup

🎯 Tasks:
	1.	Drop rows where all values except 'respondent' are missing.
	2.	Fill missing age values with the mean age.
	3.	Fill missing income with the median income.
	4.	Fill missing country with the string "Unknown"
"""
import pandas as pd 

df = pd.DataFrame({
    'respondent': [1, 2, 3, 4, 5],
    'age': [25, None, 30, None, 22],
    'income': [50000, 60000, None, None, 45000],
    'country': ['US', 'Canada', 'US', None, 'Canada']
})

new_df = df[((df['age'].notna()) | (df['income'].notna()) | (df['country'].notna())) 
            & (df['respondent'].notna())]

new_df = new_df.copy()

new_df['age'] = new_df['age'].fillna(new_df['age'].mean())
new_df['income'] = new_df['income'].fillna(new_df['income'].median())
new_df['country'] = new_df['country'].fillna('Unknown')

new_df

   respondent        age   income country
0           1  25.000000  50000.0      US
1           2  25.666667  60000.0  Canada
2           3  30.000000  50000.0      US
4           5  22.000000  45000.0  Canada

In [163]:
import pandas as pd

df = pd.DataFrame({
    'employee': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'department': ['HR', 'HR', 'Finance', 'HR', 'HR', 'Finance'],
    'year': [2022, 2022, 2022, 2023, 2023, 2023],
    'score': [85, 88, 90, 87, 84, 91]
})

# new_df = df.groupby(['department', 'year'])['score'].mean().reset_index()

pd.pivot_table(df, index=['department'], columns='year', values='score', aggfunc='mean').reset_index()

year department  2022  2023
0       Finance  90.0  91.0
1            HR  86.5  85.5

In [145]:
"""
📊 Practice Problem: Course Completion Tracker

🎯 Tasks:
	1.	Filter to only rows where "completed" == True
	2.	For each student, calculate:
	•	The number of completed courses
	•	Their average score across completed courses
	3.	Return a DataFrame with:

student | courses_completed | avg_score
"""

import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie', 'Alice'],
    'course': ['Math', 'Math', 'Math', 'English', 'English', 'English', 'History'],
    'completed': [True, True, False, True, False, True, False],
    'score': [88, 76, None, 92, None, 85, None]
})

(
    df[df['completed']]
    .groupby('student')
    .agg({'course': 'count', 'score': 'mean'})
    .reset_index()
    .rename(columns={'course': 'course_count', 'score': 'avg_score'}))

   student  course_count  avg_score
0    Alice             2       90.0
1      Bob             1       76.0
2  Charlie             1       85.0

In [139]:
"""
🎯 Tasks:
	1.	Merge the two DataFrames to include employee name, department, year, and score.
	2.	Compute the average review score per department.
	3.	Output a DataFrame:

department | avg_score

"""
import pandas as pd

employees = pd.DataFrame({
    'emp_id': [101, 102, 103, 104, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eli'],
    'department': ['HR', 'IT', 'IT', 'Finance', 'HR']
})

reviews = pd.DataFrame({
    'emp_id': [101, 102, 102, 104, 105, 105],
    'year': [2022, 2022, 2023, 2022, 2022, 2023],
    'score': [3.9, 4.2, 4.5, 3.5, 4.0, 4.1]
})


df = pd.merge(employees, reviews, how="inner", on='emp_id', suffixes=('_x','_y'))
df.groupby('department')['score'].mean().reset_index().rename(columns={'score': 'avg_score'})

  department  avg_score
0    Finance       3.50
1         HR       4.00
2         IT       4.35

In [ ]:
"""
📊 Practice Problem: Review Scores Summary

🎯 Tasks:
	1.	Filter the DataFrame to include only verified reviews.
	2.	Group by "product" and calculate the average review score.
	3.	Return a DataFrame sorted by average score descending, with columns:

product | avg_score
"""

import pandas as pd

df = pd.DataFrame({
    'product': ['A', 'A', 'A', 'B', 'B', 'C', 'C', 'C', 'C'],
    'review_score': [5, 4, 5, 3, 2, 4, 4, 5, 3],
    'verified': [True, False, True, True, False, True, False, True, True]
})

new_df = df[df['verified'] == True].groupby('product')['review_score'].mean().rename(columns={'review_score': 'avg_score'}).sort_values(by='avg_score', ascending=False).reset_index()
new_df[['product', 'avg_score']]

  product  avg_score
0       A        5.0
1       C        4.0
2       B        3.0

In [124]:
"""
🧠 Practice: Normalize and Filter Words

🎯 Task:
	1.	Normalize each sentence:
	•	Remove extra spaces
	•	Convert all words to lowercase
	2.	Flatten all the words into one list
	3.	Keep only words longer than 3 characters

⸻

Expected output (approx):

['data', 'powerful', 'python', 'great', 'data', 'analysis', 'data', 'analysis']

"""

sentences = [
    "  Data is powerful ",
    "Python is GREAT for data analysis ",
    "DATA   analysis is fun"
]

output = [w for s in sentences for w in s.strip().lower().split() if len(w) > 3]
output

['data', 'powerful', 'python', 'great', 'data', 'analysis', 'data', 'analysis']

In [76]:
"""
📊 Practice Problem: Flag Students at Risk
⸻

🎯 Tasks:
	1.	For each student, compute their average score across all subjects.
	2.	Add a new column: "at_risk" — set to True if their average is below 70, else False.
	3.	Return a DataFrame like:

student   avg_score   at_risk
Alice     65.0        True
Bob       71.0        False
Charlie   82.5        False
"""

import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie', 'Alice'],
    'subject': ['Math', 'Math', 'Math', 'English', 'English', 'English', 'History'],
    'score': [85, 72, 90, 60, 70, 75, 50]
})

new_df = df.groupby('student')['score'].mean().reset_index().rename(columns={'score': 'avg_score'})

new_df['at_risk'] = new_df['avg_score'].apply(lambda x: x < 70)
new_df

   student  avg_score  at_risk
0    Alice       65.0     True
1      Bob       71.0    False
2  Charlie       82.5    False

In [ ]:
"""

📊 Practice Problem: Top Scorer per Subject

⸻

🧠 Tasks:
	1.	For each subject, find the student(s) with the highest score.
	2.	Output a DataFrame with columns:

subject | student | score

	3.	Bonus: Sort the result by subject alphabetically.

"""
import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'subject': ['Math', 'Math', 'Math', 'English', 'English', 'English'],
    'score': [88, 79, 93, 85, 90, 87]
})
idx = df.groupby('subject')['score'].idxmax()

output = df.loc[idx]
output

   student  subject  score
4      Bob  English     90
2  Charlie     Math     93

In [55]:
"""
🧠 Practice Problem: Match Students with Their Grades

Tasks:
	1.	Merge the two DataFrames so each student is matched with their subjects and scores.
	2.	Filter the result to only include scores ≥ 90.
	3.	Sort the result by score in descending order.

Expected columns:

student_id | name | subject | score
"""
import pandas as pd

students = pd.DataFrame({
    'student_id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie']
})

grades = pd.DataFrame({
    'student_id': [1, 1, 2, 3, 3],
    'subject': ['Math', 'English', 'Math', 'English', 'Science'],
    'score': [85, 88, 79, 92, 95]
})

df = pd.merge(students, grades, how='inner', on='student_id')
df[df['score']>=90]

   student_id     name  subject  score
3           3  Charlie  English     92
4           3  Charlie  Science     95

In [52]:
"""
Great — here’s a focused pandas practice that uses filtering, grouping, and basic aggregation.

⸻

📊 Practice Problem: Average Scores by Subject

	1.	Filter the DataFrame to only include scores above 80.
	2.	Group by subject and compute the average score.
	3.	Reset the index of the result so it’s a flat DataFrame.

Expected output structure:

   subject  avg_score
0  English       86.0
1     Math       85.0
2  Science       89.0

"""
import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob'],
    'subject': ['Math', 'Math', 'Science', 'Science', 'English', 'English'],
    'score': [85, 78, 90, 88, 92, 80]
})

df[df['score'] > 80].groupby('subject', as_index=False)['score'].mean().rename(columns={'score': 'avg_score'})

   subject  avg_score
0  English       92.0
1     Math       85.0
2  Science       89.0

In [42]:
"""
🧠 Practice Problem: Extract Words with More Than 3 Letters

Task:
	1.	Use a list comprehension to extract all words longer than 3 characters.
	2.	Flatten all the words from all sentences into one list.
	3.	Your result should look something like:

['data', 'powerful', 'python', 'great', 'data', 'analysis', 'data', 'analysis']

"""

sentences = [
    "data is powerful",
    "python is great for data analysis",
    "data analysis is fun"
]


output = [x for s in sentences for x in s.split() if len(x)>3]
output

['data', 'powerful', 'python', 'great', 'data', 'analysis', 'data', 'analysis']

In [37]:
"""
	1.	Use a list comprehension to:
	•	Split each sentence into words.
	•	Flatten all the words into a single list.

output
['data', 'is', 'powerful', 'python', 'is', 'great', 'for', 'data', 'analysis', 'data', 'analysis', 'is', 'fun']    
"""

sentences = [
    "data is powerful",
    "python is great for data analysis",
    "data analysis is fun"
]

output = []

# for s in sentences:
#     spl = s.split()
#     for w in spl:
#         output.append(w)

l = [w for s in sentences for w in s.split()]
# l = {w for s in sentences for w in s.split()}

l 

# output

['data',
 'is',
 'powerful',
 'python',
 'is',
 'great',
 'for',
 'data',
 'analysis',
 'data',
 'analysis',
 'is',
 'fun']

In [ ]:
"""
Objective: Write a Python script that counts how many times each word appears in a list of sentences.

output:
{'data': 3, 'is': 3, 'powerful': 1, 'python': 1, 'great': 1, 'for': 1, 'analysis': 2, 'fun': 1}
"""
sentences = [
    "data is powerful",
    "python is great for data analysis",
    "data analysis is fun"
]

output = {}
for s in sentences:
    spl = s.split()
    for w in spl:
        output[w] = output.get(w, 0) + 1
        
# output


"""
Follow up Task:
Using your previous word count output dictionary, do the following with pandas:
	1.	Convert the dictionary into a DataFrame with columns:
	•	"word" (the word)
	•	"count" (how many times it appeared)
	2.	Sort the DataFrame by "count" in descending order.
	3.	Bonus: Filter to show only words that appear more than once.

output:
      word  count
0     data      3
1       is      3
2  analysis      2
...
"""
import pandas as pd

as_df = pd.DataFrame(list(output.items()), columns=['word', 'count']).sort_values(by='count', ascending=False).reset_index(drop=True)
df = as_df[as_df['count'] > 1]
df

       word  count
0      data      3
1        is      3
2  analysis      2

In [10]:
""" 
💻 Problem: Tuple squares

Write a list comprehension that creates a list of 
tuples in the form (n, n²) for numbers from 1 to 10.
...this problem is a variation of the one below

[(1, 1), (2, 4), (3, 9), ..., (10, 100)]
"""
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# result = [(n, n**2) for n in nums]
# result

"""
dictionary version
"""
result = {n:n**2 for n in nums}
result

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [17]:
"""
Write a list comprehension that takes a list of integers 
and returns a new list with the squares of the odd numbers only.

nums = [1, 2, 3, 4, 5, 6, 7]
# result: [1, 9, 25, 49]

"""

nums = [1, 2, 3, 4, 5, 6, 7]

result = [n**2 for n in nums if n % 2 != 0]
result

[1, 9, 25, 49]

In [ ]:
"""
Write a function that takes a sentence and returns a list of all words that:
	1.	Are longer than 3 characters
	2.	Start with a vowel (a, e, i, o, u)
	3.	Are converted to lowercase

sentence = "Apples are excellent, but Oranges often outshine"
result = vowel_words(sentence)
print(result)  # ['apples', 'excellent', 'oranges', 'often', 'outshine']
"""

sentence = "Apples are excellent, but Oranges often outshine Excellent!"

def vowel_words(sentence):
    vowels = ['a','e','i','o','u']
    result = []
    for s in sentence.split():     # i think this should fix it...
        s = s.lower().strip(',.!')
        if (len(s) > 3) and (s[0] in vowels):
            result.append(s)
    return result

vowel_words(sentence)

# Great! Here’s a cleaner version that also:

# ✅ Removes punctuation
# ✅ Handles capitalization
# ✅ Handles edge cases like "Excellent!" or "apples."

['apples', 'excellent', 'oranges', 'often', 'outshine', 'excellent']

In [ ]:
"""
Write a for loop that:
	1.	Converts each temperature to Fahrenheit (F = C * 9/5 + 32)
	2.	Appends only the Fahrenheit values that are above 75°F to a new list called hot_days_f.
"""
# temps = [22, 25, 19, 24, 28, 21, 23]
# hot_days_f = []

# for t in temps:
#     f = (t*(9/5) + 32)
#     if f > 75:
#         hot_days_f.append(f)

# hot_days_f

"""
bonus - append both F and C in a dictionary {C:F}
"""
temps = [22, 25, 19, 24, 28, 21, 23]

hot_days = {}

for t in temps:
    f = (t*(9/5) + 32)
    if f > 75:
        hot_days[t] = f 

hot_days

{25: 77.0, 24: 75.2, 28: 82.4}

In [ ]:
# You’re given a list of filenames. Write a loop that builds a dictionary where:
# 	•	Each key is a file extension (like 'txt', 'csv', 'jpg')
# 	•	Each value is the number of times that extension appears

files = [
    "report.csv", "data.csv", "image.jpg", "notes.txt",
    "summary.txt", "presentation.ppt", "photo.jpg"
]

solution = {}


for f in files:
    extensions = f[-3:]
    solution[extensions] = solution.get(extensions,0) + 1

solution

{'csv': 2, 'jpg': 2, 'txt': 2, 'ppt': 1}

In [ ]:
# Write a loop that:
# 	•	Tallies how many names start with each letter
# 	•	Uses .get() to safely update counts in a dictionary

names = [
    "Alice", "Aaron", "Bob", "Brenda", "Charlie", "Catherine", "David", "Diana"
]

first_letter = []
solution = {}

for n in names:
    k = n[0]
    solution[k] = solution.get(k,0) + 1

solution

{'A': 2, 'B': 2, 'C': 2, 'D': 2}

In [2]:
# Use a for loop to tally how many votes each candidate received

votes = [
    'Alice', 'Bob', 'Alice', 'Eve', 'Bob', 'Alice', 'Eve', 'Eve', 'Bob', 'Alice'
]

votes_dict = {}

for v in votes:
    votes_dict[v] = votes_dict.get(v, 0) + 1

votes_dict

{'Alice': 4, 'Bob': 3, 'Eve': 3}

In [ ]:
# Task:
# Write a Python function that takes a list of strings (sentences) and returns a dictionary 
# with the frequency of each word (case-insensitive).


sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "The dog barked, and the fox ran away!"
]
s_list = []

for s in sentences:
    s_split = s.split()
    for w in s_split:
        s_list.append(w.lower().strip(',.!'))

s_unique = []
for word in s_list:
    if word not in s_unique:
        s_unique.append(word)

a_dict = {}
for j in s_unique:
    a_dict[j] = s_list.count(j)

a_dict

{'the': 4,
 'quick': 1,
 'brown': 1,
 'fox': 2,
 'jumps': 1,
 'over': 1,
 'lazy': 1,
 'dog': 2,
 'barked': 1,
 'and': 1,
 'ran': 1,
 'away': 1}

In [33]:

vowels = ['a','e','i','o','u']
words = ['apple', 'sky', 'education', 'loop']
solution = []
for w in words:
    counter = 0
    for l in w:
        if l in vowels:
            counter += 1
    solution.append(counter)

solution

[2, 0, 5, 2]

In [39]:
# get longest word in a text
text = "Learning Python with practicing builds strong coding muscle memory"
words = text.split()
lengths = []
for w in words:
    lengths.append(len(w))

biggest = max(lengths)
lengths.index(biggest)

3

In [ ]:
"""
Find the distance between the two furthest apart values in a list.
Create a dist function, receiving a list of numbers (integers or floating points), 
and returning the bigger distance between any two given values, 
so typically the distance between the biggest and the smallest, like:
>>> dist([1, 2, 3])
2
"""

In [ ]:
"""
Write a function named from_roman_numeral that return the value of a given roman numeral.

if next > curr, then -=curr
else +=curr
upper...

"""

roman_str = 'XLIX'

def from_roman_numeral(roman_str):
    conversion = {'I':1, 'V':5, 'X':10, 'L':50 ,'C':100,'M':1000}
    value = 0
    for n in range(len(roman_str)): # determine value, and add to total
        val = conversion[roman_str[n]]
        if n+1 < len(roman_str): 
            next_val = conversion[roman_str[n+1]]
            if val < next_val:
                value -= val
                continue
        value += val

    return(value)

from_roman_numeral(roman_str)
# can this be shortened using tech support?

49

In [ ]:
"""
Write a function named to_roman_numeral that converts integers to roman numerals.

"""

to_numeral = 24

conversion = {1000:'M', 100:'C', 50:'L', 10:'X', 5:'V', 1:'I' }
num_list = list(conversion.keys())
output = ''

while to_numeral > 0:

    max_key = max([x for x in num_list if x <= to_numeral], default=1)
    max_val = conversion[max_key]
    max_key_prior = num_list.index(max_key) - 1      # account for errors when this doesnt exist
    max_val_prior = conversion[num_list[max_key_prior]]

    output += max_val
    if 4 * max_key <= to_numeral:
        output += max_val_prior
        to_numeral -= 4 * max_key
    else:
        to_numeral -= max_key
        
    

output

'XXIV'

In [109]:
"""
You found a safe. There's a numeric keypad on it...
The keypad is dirty, thanks to this you can easily spot that numbers 1, 5, and 8 are frequently used. 
It's so clear that you guess no other digit is in use in this code.
Write a script printing all combinations of 4 digits that use all of those used digits.
Output one combination per line, separate digits using spaces, so your output should look like:
1 1 5 8
1 5 5 8
1 5 8 8
"""

"\nYou found a safe. There's a numeric keypad on it...\nThe keypad is dirty, thanks to this you can easily spot that numbers 1, 5, and 8 are frequently used. \nIt's so clear that you guess no other digit is in use in this code.\nWrite a script printing all combinations of 4 digits that use all of those used digits.\nOutput one combination per line, separate digits using spaces, so your output should look like:\n1 1 5 8\n1 5 5 8\n1 5 8 8\n"

In [ ]:
"""
Write a function combining two strings so they are displayed side by side, separated by a column of pipe (|) symbols, like this:
Lorem ipsum dolor sit amet, consectetur|Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Sed non risus.        |adipiscing elit. Sed non risus.        
Suspendisse lectus tortor, dignissim   |Suspendisse lectus tortor, dignissim   
sit amet, adipiscing nec, utilisez sed |sit amet, adipiscing nec, utilisez sed 
sin dolor.                             |sin dolor. 

This function will also take a 3rd, optional, parameter named width representing the maximum width allowed, defaulting to 79, so the function prototype is:
"""

In [ ]:
"""
Implement the fill_magic_square function.
It takes a single argument: a numpy.array of integers representing a partially filled magic square. Holes are represented using zeros.
Your fill_magic_square function will have to find and fill the gaps in the square.
Do not return a value, just modify the square in-place.
Beware, my magic squares may contain any natural number (> 0), I do not restrict myself to magic squares with numbers from 1 to square_size ** 2.

easy_square = np.array([
    [2, 7, 6],
    [9, 0, 1],
    [4, 3, 8],
])
fill_magic_square(easy_square)
print(easy_square)

Should give:
array([[ 2, 7, 6 ],
       [ 9, 5, 1 ],
       [ 4, 3, 8 ]]])

"""

##### **Hangman ---> Python game by E**

In [ ]:
# num_letters = int(input("welcome to hell...I mean, hangman. Six wrong guesses and I win. hahaha...how many letters do you want the answer to have? "))

# # generate a word with num_letters letters
# answer_string = "doggy"
# answer_list = []
# starting_list = []

# for a in answer_string:
#     answer_list.append(a)

# for s in range(num_letters):
#     starting_list.append("-")

#     # change the above to a string? "-"

# # other variables
# guess_list = []
# chances = 6
# chance_counter = 0

In [ ]:
# guess = input(f"the word is {starting_list}. You get {chances} chances - guess a letter, or guess the word: ")
# if guess == answer_string:
#     print("damn, you're good. I quit!")

# while (guess != answer_string) & (chance_counter < 6) & (starting_list != answer_list):
#     # word is selected
#     if len(guess) > 1:

#     # word is correct
#         if guess == answer_string:
#             print("you WIN!")

#     # word is incorrect
#         else:
#             chance_counter += 1
#             guess = input(f"nope! that's {chance_counter} out of 6 guesses. guess a letter, or the word: {starting_list}")


#     # letter is selected
#     else:
#         if guess in guess_list:
#             guess = input(f"you guessed that letter already - try a different one {starting_list}: ")
#     # letter is correct
#         elif guess in answer_string:
#             yes_list = []
#             guess_list.append(guess)
#             for letter_ind in range(len(answer_list)):
#                 if answer_list[letter_ind] == guess:
#                     yes_list.append(letter_ind)
            
#             for m in yes_list:
#                 starting_list[m] = guess
#             if starting_list == answer_list:
#                 print("well played. I concede - you win.")        
#                 break  
#             else:
#                 guess = input(f"Sure, that letter's in there: {starting_list}. guess a letter, or the word: ")

    
#     # letter is incorrect
#         else:
#             guess_list.append(guess)
            
#             if chance_counter == 6:
#                 print("Got 'eeeeem! I win")
#                 break
#             else:
#                 guess = input(f"nope! that's {chance_counter} out of 6 guesses. guess a letter, or the word: {starting_list}")
#                 chance_counter += 1

well played. I concede - you win.

In [ ]:
# # Provide a script that prints the number of words in the given paragraph.
# # I prefilled the answer box with the paragraph, in a variable, but in case you lose it, here it is:

# #   - remove punctuation
# #   - all lowercase

# # whetting_your_appetite = "Python is an easy to learn, powerful programming language. It has efficient high level data structures and a simple but effective approach to object oriented programming. This tutorial introduces the reader informally to the basic concepts and features of the Python language and system. For a description of standard objects and modules..."
# word_count = "I am using Python. This is a string with has words. I am counting the words, words, words, using python python python python python"

# word_split = word_count.split()
# counter = 0

# # count total words
# word_list = []
# for word in word_split:
#     word_list.append(word.lower().strip(".,"))
#     counter += 1

# counter
# # word_list

# # can you also count the number of each word - output as a list

# deduped = []
# for i in word_list:
#     if i not in deduped:
#         deduped.append(i)
#     else:
#         deduped = deduped

# # deduped

# word_dict = {}

# for k in deduped:
#     val = 0
#     for v in word_list:
#         if k == v:
#             val += 1
#         word_dict[k] = val

# word_dict

24

In [ ]:
# # Ask the user for a number and determine whether the number is prime or not. 

# num = int(input("let's check a numbers prime-ability. enter one: "))
# counter = 0
# factors = []
# for i in range(1, num + 1):
#     if num % i == 0:
#         counter += 1
#         factors.append(i)
#     else:
#         counter = counter

# print(counter)
# print(factors)
# if counter <= 2:
#     print("PRIME")
# else:
#     print("unprime")

4
[1, 3, 127, 381]
unprime